<?php include_once("include/header_inner.php"); ?>

	<div id="content">
		
		<h2>Terms of Service</h2>
		
		<p>I understand and acknowledge that by agreeing to use this website for testing services that I must be a resident of any state within the United States.  I ALSO UNDERSTAND AND ACKNOWLEDGE THAT IF I VIOLATE THIS CONDITION OR ANY OTHER ONE OF THESE TERMS AND CONDITIONS, PINPOINTMD WILL NOT PROVIDE THE RESULTS OF MY TEST.</p>
		<p>By using PINPOINTMD, I agree to the following:</p>
		<ul>
			<li>I am 18 years of age or older.&nbsp;</li>
			<li>I am the person being tested.&nbsp;</li>
			<li>I authorize PINPOINTMD to test me for the sexually transmitted disease or sexually transmitted infection (STD) tests I have selected.&nbsp;</li>
			<li>I will provide a blood/urine/swab sample that is collected either at a Labcorp (a Patient Service Center), Quest Diagnostics (a Patient Service Center), or through the Home Collection Kit.&nbsp;</li>
			<li>I understand and acknowledge that I will usually have access to my test results online within 3 business days after providing my sample at a Quest Diagnostics (a Patient Service Center or PSC) or Labcorp, or if using the Home Collection Kit within 3-7 business days after the sample is received at the testing laboratory. If I do not receive my results within 5 business days it is my responsibility to contact PINPOINTMD and notify them the results have not been received because PINPOINTMD does not know when I got tested and therefore when to expect the results.  While results are normally returned within 5 business days, it is possible that results can take longer especially in the case of Herpes tests which can only be tested in certain labs and are shipped to those labs to be tested. I</li>
			<li>n the unlikely event of a lab error, refunds will be at the discretion of PINPOINTMD.&nbsp;</li>
			<li>I understand and acknowledge that my requisition form from PINPOINTMD is valid for 6 months from the date of purchase. There will be no refund available if I do not get tested within this time period.&nbsp;</li>
			<li>I understand and acknowledge that I am not being tested for every sexually transmitted disease.&nbsp;</li>
			<li>I understand and acknowledge that if my test results are positive, PINPOINTMD may report my results to my State&rsquo;s local or state departments of public health as required by law. Federal, state and local law require that my results be kept confidential, but some states require named reporting.&nbsp;</li>
			<li>I understand and acknowledge that if I am testing in New York, New Jersey, or Rhode Island, I will be paying PINPOINTMD a fee of $125 for physician review and authorization to test. I also understand that I will be paying a lab fee to my Labcorp testing facility upon arrival. The fee will vary depending on my testing package.&nbsp; </li>
			<li>I understand and acknowledge that while PINPOINTMD&rsquo;s STD testing service uses the same FDA-approved tests that physicians use and are highly accurate (highly specific and highly sensitive), there is a remote possibility of a false positive or false negative result. A false positive result can indicate that a person tests positive for the appropriate indicators, when in fact, they are negative. A false negative result can have 2 possible meanings, a person can be infected, but their body has not yet produced the appropriate indicators or their body is producing the appropriate indicators but the test failed to detect the indicators.&nbsp;</li>
			<li>I understand that it is my responsibility to to properly administer and return my home kit test. If the test is not properly run due to a collection error, there is no refund available. We will send you one additional home kit at no cost. In the unlikely event that you are unable to receive your home kit or the Quest lab never receives it, we can send you 1 other kit at no additional cost.&nbsp;</li>
			<li>I understand and acknowledge that PINPOINTMD will take all privacy and security precautions to protect my personal confidential information. PINPOINTMD is in compliance with Federal and State laws and related Rules and Regulations to protect my confidential protected health information ("PHI") as defined by the Health Insurance Portability and Accountability Act of 1996 ("HIPAA") and the American Recovery and Reinvestment Act of 2009 (the "Stimulus Package"), as it is understood today.&nbsp;</li>
			<li>I understand that the Stimulus Package is new and untested and that all resulting implications of such are not yet known. PINPOINTMD is not responsible for a customer&rsquo;s disclosure or loss of his or her Confirmation Number.&nbsp;</li>
			<li>I agree to notify the company immediately in writing if my Confirmation Number is disclosed or lost so my PHI can be protected.&nbsp;</li>
			<li>I release and hold PINPOINTMD, Medivo, Quest Diagnostics, Labcorp, and/or any other entity that supports this website or its services, harmless from any injury or personal damage that occurs.&nbsp;PINPOINTMD complies with all regulations provided it by federal, state and local departments of public health.&nbsp;</li>
			<li>I understand that while PINPOINTMD attempts to provide me the many counseling options (online, phone-based counselors, and phone-based physician counseling) PINPOINTMD bears no responsibility to provide me medical or psychological care regardless of my test results. We recommend you talk to your local physician, review the Centers for Disease Control and Prevention (CDC) website at http://www.cdc.gov, or contact The American Social Health Association at http://www.ashastd.org.&nbsp;</li>
			<li>In the event that I want to cancel my test prior to getting tested and before going to the Quest Diagnostics patient service center or Labcorp, I will be refunded 80% of the fees paid due to direct expenses related to getting the requisition processed. Refunds after going to the Quest Diagnostics patient service center will be wholly at the discretion of PINPOINTMD.  No refunds will be given after results are available, with no exceptions. &nbsp;PINPOINTMD services and materials are for informational purposes only and are not a substitute for medical advice, diagnosis or treatment. In the event of a positive test result, a prescription may be available from PINPOINTMD&rsquo;s physician for an additional cost. PINPOINTMD and Medivo manage a confidential program with stringent protocols in place to maintain the confidentiality of my information. Only I will receive a copy of my personalized wellness report.&nbsp;</li>
			<li>I understand and acknowledge that should I choose to I am solely responsible for forwarding the test results to my personal physician and for initiating follow up with my personal physician for medical treatment or to obtain an interpretation of the test results.&nbsp;</li>
			<li>I understand and acknowledge that my participation in this program is strictly voluntary. By participating in a program that involves laboratory testing, I consent to the withdrawal of blood buy needle or lancet, and to the testing of any blood specimen by the Clinical Lab Improvement Amendment ("CLIA") licensed reference laboratory (CLIA Lab) associated with this program.&nbsp;</li>
			<li>I understand and acknowledge that if I choose to participate in this service, I provide my authorization for Medivo and the CLIA Lab to disclose the data and outcomes of my health risks assessment and test results in a confidential manner as permitted or required by law. In the event my data is shared with Medivo staff, contractors, affiliates, health care professionals or third party vendors, including the CLIA Lab, it will be limited to only those individuals directly involved with the provision of PWN services and preparation of the personal result report. I understand and acknowledge that the results derived from this testing are to be considered informational only and do not constitute the practice of medicine, interpretation of test results, or diagnosis of any particular disease state or medical condition.&nbsp;</li>
			<li>I understand and acknowledge that I must see my personal medical provider for interpretation of test results, diagnosis of disease, and/or medical condition.&nbsp;</li>
			<li>I understand and acknowledge that while the risk of harm to me is small, persons have been injured while their blood is withdrawn, and that tests results are not always completely accurate. I HEREBY FULLY ASSUME THE RISK for injury or loss which may be sustained by needle or lancet. I HEREBY FULLY RELEASE PINPOINTMD, Medivo, Quest Diagnostics, Labcorp, and any provider of services connected with this website or services, or sponsor of this program, the person withdrawing my blood and his or her employer, and the testing laboratory and its employees and contractors from all liability, claims, demands and causes of action for any loss or injury which may be sustained in connection with the withdrawal of blood, testing, test results, disclosure of tests results as described above or otherwise in connection with this service or program in which I am participating.&nbsp;</li>
			<li>By agreeing to the testing, I and the physician responsible for the test order are requesting that a copy of the test results be provided to me, the participant, directly.</li>
			<li>Current copies of the PINPOINTMD Privacy Practices and Online Privacy Policy are available.</li>
		</ul>

<?php include_once("include/footer.php"); ?>