<?php
$templates = Mage::helper('sendmail')->getTemplates();
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<form action="" onsubmit="return " id="sendmailForm" method="post">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields" style="display:none;">
                <div class="field">
                    <label for="email"><em>*</em><?php echo Mage::helper('sendmail')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('sendmail')->__('Email') ?>" value="" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>

            <li class="fields">
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('sendmail')->__('Select Template') ?></label>
                    <div class="input-box">

                        <select name="template" id="template" title="<?php echo Mage::helper('sendmail')->__('Email') ?>"  class="input-text required-entry " >
                            <option value="">Select Template</option>
                            <?php
                            foreach ($templates as $i => $v) {
                                echo "<option value='" . $v['id'] . "'>" . $v['name'] . "</option>";
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </li>

        </ul>
    </div>
    <div class="buttons-set form-buttons btn-only">
        <button type="button" onclick="addNotification()" class="button" title="<?php echo Mage::helper('sendmail')->__('Submit') ?>"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
    <p class="required"><?php echo Mage::helper('sendmail')->__('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    //<![CDATA[
    var sendmailForm = new VarienForm('sendmailForm', true);
    function addNotification(){ 

        var url = '<?php echo Mage::helper('adminhtml')->getUrl('sendmail/adminhtml_index/send'); ?>';
        new Ajax.Request(
        url,
        { 
            method: 'post', 
            parameters: {email: $('email').value, template: $('template').value},
            onComplete: function(transport){
                $('messages_product_view').innerHTML = transport.responseText;
            }}
    );
    }

    //]]>
</script>
