<!-- Google Website Optimizer Control Script -->
<script>
function utmx_section(){}function utmx(){}
(function(){var k='3040539836',d=document,l=d.location,c=d.cookie;function f(n){
if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.indexOf(';',i);return escape(c.substring(i+n.
length+1,j<0?c.length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;
d.write('<sc'+'ript src="'+
'http'+(l.protocol=='https:'?'s://ssl':'://www')+'.google-analytics.com'
+'/siteopt.js?v=1&utmxkey='+k+'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='
+new Date().valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
'" type="text/javascript" charset="utf-8"></sc'+'ript>')})();
</script>
<!-- End of Google Website Optimizer Control Script -->
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['gwo._setAccount', 'UA-10462432-2']);
  _gaq.push(['gwo._trackPageview', '/3040539836/test']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!-- End of Google Website Optimizer Tracking Script -->

<?php

//echo "<pre>";  print_r(Mage::getModel('core/session')->getData()); echo "</pre>";

$this->resetCart();

$_products = $this->getProducts();

$state = Mage::getSingleton('core/session')->getOrderState();

$sZip = Mage::getSingleton('core/session')->getZip();

if ($sZip) {

	$sesZip = $sZip;

} else {

	$sesZip = 'Zip Code';

}


//echo "<pre>"; print_r(Mage::getSingleton('core/session')->getData()); echo "</pre>"; 

?>
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
				
	if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder") ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;
var ultimatePackage = 249;

var indiTestOrig = new Array();
	indiTestOrig[0] = <?php echo round($_products['chlamydia-lab']['price']);?>;
	indiTestOrig[1] = <?php echo round($_products['gonorrhea-lab']['price']);?>;
	indiTestOrig[2] = <?php echo round($_products['hiv-lab']['price']);?>;
	indiTestOrig[3] = <?php echo round($_products['syphilis-lab']['price']);?>;
	indiTestOrig[4] = <?php echo round($_products['oralherpes-lab']['price']);?>;
	indiTestOrig[5] = <?php echo round($_products['genitalherpes-lab']['price']);?>;
	indiTestOrig[6] = <?php echo round($_products['hepatitis-b-lab']['price']);?>;
	indiTestOrig[7] = <?php echo round($_products['hepatitis-c-lab']['price']);?>;
	
var homeTestOrig = new Array();
	homeTestOrig[0] = <?php echo round($_products['chlamydia-home']['price']);?>;
	homeTestOrig[1] = <?php echo round($_products['trichomoniasis-home']['price']);?>;
	homeTestOrig[2] = <?php echo round($_products['gonorrhea-home']['price']);?>;
	homeTestOrig[3] = <?php echo round($_products['hiv-home']['price']);?>;
	
var indiSkuArr = new Array();
	indiSkuArr[0] = 'chlamydia-lab';
	indiSkuArr[1] = 'gonorrhea-lab';
	indiSkuArr[2] = 'hiv-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'oralherpes-lab';
	indiSkuArr[5] = 'genitalherpes-lab';
	indiSkuArr[6] = 'hepatitis-b-lab';
	indiSkuArr[7] = 'hepatitis-c-lab';
	
var homeSkuArr = new Array();
	homeSkuArr[0] = 'chlamydia-home';
	homeSkuArr[1] = 'trichomoniasis-home';
	homeSkuArr[2] = 'gonorrhea-home';
	homeSkuArr[3] = 'hiv-home';
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		total = 0;
		
		price = 0;
		
		cartArr = new Array();
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = document.getElementById(el).value;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
				document.getElementById('complete_package_hidden').value = 0;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	// if (cartArr.length == 0) {
// 	   		
	   		// total = 0;
// 	   		
	   	// }
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		document.getElementById('expert_package_hidden').value = 0;
		document.getElementById('complete_package_hidden').value = 0;
		
		document.getElementById('expert_package').checked = false;
		document.getElementById('complete_package').checked = false;
		
		document.getElementById('package').value = "";
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
				
		if (cartArr.length == 2 && el.indexOf('lab') > 0) {
		
			discount = 30;
					
		} 
		
		if (cartArr.length == 3 && el.indexOf('lab') > 0) {
		
			discount = 75;
					
		}
		
		if (cartArr.length == 4 && el.indexOf('lab') > 0) {
		
			discount = 165;
					
		}
		
		if (cartArr.length == 5 && el.indexOf('lab') > 0) {
		
			discount = 205;
					
		}
		
		if (cartArr.length == 6 && el.indexOf('lab') > 0) {
		
			discount = 295;
					
		}
		
		if (cartArr.length == 7 && el.indexOf('lab') > 0) {
		
			discount = 385;
					
		}
		
		if (cartArr.length == 8 && el.indexOf('lab') > 0) {
		
			discount = 475;
					
		}
		
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 45;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 106;
    			
    			}
			}
		
		}
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 70;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 135;
    			
    			}
			}

		}
		
		if (cartArr.length == 4 && el.indexOf('home') > 0 ) {
		
			discount = 196;
		
		}
		
	
	   total = total + price;	
	   
	   <?php } else  { ?>
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	if (cartArr.length == 0) {
	   		
	   		total = 0;
	   		
	   	}
	   	
	   <?php } ?>
	
	   document.getElementById('widget_total').innerHTML = '$'+(total-discount);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked && !document.getElementById('expert_package').checked && !document.getElementById('complete_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'complete_package') {
		
		document.getElementById('expert_package-cart').style.display = 'none';
		document.getElementById('complete_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
		
		
	
	} else if (el == 'expert_package') {
		
		document.getElementById('complete_package-cart').style.display = 'none';
		document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	document.getElementById('complete_package-cart').style.display = 'none';
	
	document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>
<div class="clear"></div>
            <div class="sep10"></div>

<script>utmx_section("Product Widget")</script>
			
            <div id="content">
            	
                <div id="order">
<br /><br />
                    <div id="order_module"> 
                    	<form name="orderWidget" id="orderWidget" method="post" action="/customroute/index/checkout">
                            <div id="at_home">
                                <div class="header">At-Home Testing</div>
                                <div class="content">
                                    <h4><span class="light_blue">Free</span> priority shipping</h4>
                                    <ul>
                                    	
                                    	<li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="<?php echo $_products['chlamydia-home']['price'];?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['chlamydia-home']['id'];?>);toggleCartElement(this.id);" id="chlamydia-home" name="homeTest[chlamydia-home]" />Chlamydia</li>
                                        <li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="<?php echo $_products['gonorrhea-home']['price'];?>" id="gonorrhea-home" onClick="updateWidgetTotal(this.id,<?php echo $_products['gonorrhea-home']['id'];?>);toggleCartElement(this.id);" name="homeTest[gonorrhea-home]" />Gonorrhea</li>
                                        <li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="<?php echo $_products['trichomoniasis-home']['price'];?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['trichomoniasis-home']['id'];?>);toggleCartElement(this.id);" id="trichomoniasis-home" name="homeTest[trichomoniasis-home]" />Trichomoniasis</li>
                                       
                                        <li><input type="checkbox" value="<?php echo $_products['hiv-home']['price'];?>" id="hiv-home" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-home']['id'];?>);toggleCartElement(this.id);" name="homeTest[hiv-home]" />HIV Express<span class="small">(next day results)</span></li>
                                    </ul>
                                </div>
                                <div class="footer">
                                	<span class="price">$105 each</span>
                                    <span class="info">discounts for multiple tests</span>
                                </div>
                            </div> <!-- /at_home -->
                            
                            <div class="sep">OR</div>
                            
                            <div id="lab_tests">
                            
                            	<div class="header">Local, Private Lab Testing</div>
                                
                                <div class="item" id="individual_tests">
                                	<div class="content">
                                    	<h4>Individual Tests</h4>
                                        <ul>
                                        	<li><input type="checkbox" value="<?php echo $_products['chlamydia-lab']['price'];?>" id="chlamydia-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['chlamydia-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[chlamydia-lab]" />Chlamydia</li>
                                            <li><input type="checkbox" value="<?php echo $_products['gonorrhea-lab']['price'];?>" id="gonorrhea-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['gonorrhea-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[gonorrhea-lab]" />Gonorrhea</li>
                                            <li><input type="checkbox" value="<?php echo $_products['hepatitis-b-lab']['price'];?>" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-b-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" />Hepatitis B</li>
                                            <li><input type="checkbox" value="<?php echo $_products['hepatitis-c-lab']['price'];?>" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-c-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" />Hepatitis C</li>
                                            <li><input type="checkbox" value="<?php echo $_products['oralherpes-lab']['price'];?>" id="oralherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['oralherpes-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[oralherpes-lab]" />Oral Herpes</li>
                                            <li><input type="checkbox" value="<?php echo $_products['genitalherpes-lab']['price'];?>" id="genitalherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['genitalherpes-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[genitalherpes-lab]" />Genital Herpes</li>
                                            <li><input type="checkbox" value="<?php echo $_products['hiv-lab']['price'];?>" id="hiv-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hiv-lab]" />HIV</li>
                                            <li><input type="checkbox" value="<?php echo $_products['syphilis-lab']['price'];?>" id="syphilis-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['syphilis-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" />Syphilis</li>
                                        </ul>
                                    </div>
                                    <div class="footer">
                                    	<span class="price">$90 each</span>
                                        <span class="info">discounts for multiple tests</span>
                                    </div>
                                </div> <!-- /individual_tests -->
                                
                                <div class="item" id="basic_package">
                                	<div class="content">
                                    	<h4>Basic Package</h4>
                                        <ul>
                                        	<li>Chlamydia</li>
                                            <li>Gonorrhea</li>
                                            <li>Genital Herpes</li>
                                            <li>HIV</li>
                                        </ul>
                                    </div>
                                    <div class="footer">
                                    	<div class="price">$<?php echo round($_products['basic-4-pack-package-lab']['price']);?></div>
                                        <div class="add_to_cart">
                                        	<input type="radio" id="complete_package" value="<?php echo round($_products['basic-4-pack-package-lab']['price']);?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['basic-4-pack-package-lab']['id'];?>);toggleCartElement(this.id);" name="testPackage" /> Add to cart
                                        	<input id="complete_package_hidden" type="hidden" value="<?php echo round($_products['basic-4-pack-package-lab']['price']);?>" name="pack_<?php echo $_products['basic-4-pack-package-lab']['id'];?>">
                                        </div>
                                    </div>
                                </div> <!-- /basic_package -->
                                
                                <div class="item" id="ultimate_package">
                                	<div class="content">
                                    	<h4>Complete Package</h4>
                                        <ul>
                                        	<li>Chlamydia</li>
                                            <li>Gonorrhea</li>
                                            <li>Hepatitis B</li>
                                            <li>Hepatitis C</li>
                                            <li>Oral Herpes</li>
                                            <li>Genital Herpes</li>
                                            <li>HIV</li>
                                            <li>Syphilis</li>
                                        </ul>
                                    </div>
                                    <div class="footer">
                                    	<div class="price">$<?php echo round($_products['ultimate-8-pack-package-lab']['price']);?></div>
                                        <div class="add_to_cart">
                                        	<input type="radio" id="expert_package" value="<?php echo round($_products['ultimate-8-pack-package-lab']['price']);?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>);toggleCartElement(this.id);" name="testPackage" /> Add to cart
                                        	<input id="expert_package_hidden" type="hidden" name="pack_<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>" value="<?php echo round($_products['ultimate-8-pack-package-lab']['price']);?>">
                                        </div>
                                    </div>
                                </div> <!-- /ultimate_package -->
                                
                            </div> <!-- /lab_tests -->
                            
                            <div class="sep sep_arrow">&nbsp;</div>
                            
                            <div id="your_order">
                            	<div class="header">Your Order</div>
                                <div class="content">
                                	<div id="ow_list">
                                	
                 <div style="display:none;" id="chlamydia-home-cart">&bull;&nbsp;Chlamydia</div>
                 <div style="display:none;" id="gonorrhea-home-cart">&bull;&nbsp;Gonorrhea</div>
                 <div style="display:none;" id="trichomoniasis-home-cart">&bull;&nbsp;Trichomoniasis</div>
                 <div style="display:none;" id="hiv-home-cart">&bull;&nbsp;HIV Express</div>
                 
                 <div style="display:none;" id="chlamydia-lab-cart">&bull;&nbsp;Chlamydia</div>
                 <div style="display:none;" id="gonorrhea-lab-cart">&bull;&nbsp;Gonorrhea</div>
                 <div style="display:none;" id="hepatitis-b-lab-cart">&bull;&nbsp;Hepatitis B</div>
                 <div style="display:none;" id="hepatitis-c-lab-cart">&bull;&nbsp;Hepatitis C</div>
                 <div style="display:none;" id="oralherpes-lab-cart">&bull;&nbsp;Oral Herpes</div>
                 <div style="display:none;" id="genitalherpes-lab-cart">&bull;&nbsp;Genital Herpes</div>
                 <div style="display:none;" id="hiv-lab-cart">&bull;&nbsp;HIV</div>
                 <div style="display:none;" id="syphilis-lab-cart">&bull;&nbsp;Syphilis</div>
                 
                 
                 
                 <div id="complete_package-cart" style="display:none;">
                 <div id="chlamydia-lab-cart-cp">&bull;&nbsp;Chlamydia</div>
                 <div id="gonorrhea-lab-cart-cp">&bull;&nbsp;Gonorrhea</div>
                 <div id="genitalherpes-lab-cart-cp">&bull;&nbsp;Genital Herpes</div>
                 <div id="hiv-lab-cart-cp">&bull;&nbsp;HIV</div>
                 </div>
                 
                 <div id="expert_package-cart" style="display:none;">
                 <div id="chlamydia-lab-cart-ep">&bull;&nbsp;Chlamydia</div>
                 <div id="gonorrhea-lab-cart-ep">&bull;&nbsp;Gonorrhea</div>
                 <div id="hepatitis-b-lab-cart-ep">&bull;&nbsp;Hepatitis B</div>
                 <div id="hepatitis-c-lab-cart-ep">&bull;&nbsp;Hepatitis C</div>
                 <div id="oralherpes-lab-cart-ep">&bull;&nbsp;Oral Herpes</div>
                 <div id="genitalherpes-lab-cart-ep">&bull;&nbsp;Genital Herpes</div>
                 <div id="hiv-lab-cart-ep">&bull;&nbsp;HIV</div>
                 <div id="syphilis-lab-cart-ep">&bull;&nbsp;Syphilis</div>
                 </div>
                 
                             	
                                	</div>

                                </div>
                                    
                                <div class="total">
                                	Total
                                    <span id="total_price"><div id="widget_total">$0</div></span>
                                </div>
                                <input type="button" onclick="checkEmpty();" class="submit btn_orange_32_reflection" value="checkout" style="width: 125px;" />
                            </div> <!-- /your_order -->
                  <input type="hidden" id="package" name="package" value="">          
						</form>                    	    
                    </div> <!-- /order_module -->
                    
                    <div class="clear">&nbsp;</div>
                    <!-- <div class="sep20">&nbsp;</div>
                    <div class="sep20">&nbsp;</div> -->
                    <div class="sep20">&nbsp;</div>
                    <div class="sep20">&nbsp;</div>
                     <div class="sep20">&nbsp;</div>
                    
                    <div class="trusted">
                    	<span class="intro">
                        	Trusted by our customers and the sexual health community
                        </span>
                        <img src="/media/images/trusted_logos.png" />
                        <div class="reviews">
                        	<span class="orange">4.5/5</span> star customer reviews <img src="/media/images/reviews_stars_small_transp.png" />
                        </div>
                    </div>
                        
                </div> <!-- /order -->
                
            </div> <!-- /content -->
			
</noscript>			