<?php

	$localepage = Mage::registry('localepage');
	
	$values = unserialize($localepage->getValues());
		
?>                
            <div class="clear"></div>
            <div class="sep10"></div>
            	
            <div id="content">
				<div id="lp_generic">
                
                    <div id="lp_generic_banner">
                    	<h1><?php echo  $values['h1'];?></h1>
                        
                        <div class="benefits">
                        	<a id="testing_options_link" href="/std-testing-options" class="btn_orange_shadow">See Testing Options</a>
                            <h2><?php echo  $values['h2'];?></h2>
                            <ul>
                            	<li><span class="orange">Test Today:</span> No wait. Order and test for STDs today. Get results within 3 days through confidential online patient portal.</li>
                                <li><span class="orange">Highest Accuracy Available:</span> Same trusted labs used by doctors and hospitals nationwide. </li>
                                <li><span class="orange">Free Physician Consult:</span> Get the facts about STDs through a complimentary consultation with an in-house physician.</li>
                                <li><span class="orange">Convenient:</span> STD tests available via at-home STD testing kits and at over 4,000+ nationwide testing centers.</li>
                                <li><span class="orange">Confidential:</span> No insurance records. STD test results are  private.</li>
                            </ul>
                        </div> <!-- /.benefits -->
                        
                        <div class="results">
                        	<h2>Results in <span class="orange">3 days</span> </h2>
                            <p>and prescriptions available if positive</p>
                        </div> <!-- /.results -->
                        
                    </div> <!-- /lp_generic_banner -->
                    
                    <h2><?php echo  $values['subheading'];?></h2>
                    <h3><?php echo  $values['body1_h3'];?></h3>
                    <p><?php echo  $values['body1_content'];?></p>
                    <h3><?php echo  $values['body2_h3'];?></h3>
                    <p><?php echo  $values['body2_content'];?></p>
                    <h3><?php echo  $values['body3_h3'];?></h3>
                    <p><?php echo  $values['body3_content'];?></p>
                    <h4><?php echo  $values['body4_h4'];?></h4>
                    <p><?php echo  $values['body4_content'];?></p>
                    <h4><?php echo  $values['body5_h4'];?></h4>
                    <p><?php echo  $values['body5_content'];?></p>
                    
                </div> <!-- /lp_generic -->
            </div> <!-- /content -->
            

