<?php

	$dynamic = Mage::registry('dynamic');	
	
	//print_r($dynamic);

?>
            
            <div class="clear"></div>
            <div class="sep10"></div>
            
            <div id="breadcrumbs">
            	<a href="frontpage.html">Home</a>
                <span class="separator"> > </span>
                <a href="#" class="current">STD Testing by State</a>
            </div> <!-- /breadcrumbs -->
            	
            <div id="content">

				<div id="left_col">
                	
                    <div id="std_testing_state_module">
                        <h1 class="page-title">Over 4,000 locations to test for STDs. </h1>
                        <h3>Find a private testing location near you</h3>
                        
                        <div class="bg_grey_round">
                        	<form action="" method="get">
                            	<label for="zip_code">Enter zip code: </label>
                            	<input type="text" class="text" name="zip_code" />
                                <input type="submit" class="submit btn_orange_reflection" value="find" />
                            </form>
                        </div>
                        
                        <div id="std_state_search_results">
                        
	                        <h3>Many labs open until 5:00 p.m. or later. Order and test as soon as today.</h3>
                            
                            <div class="item">
                            	<h4>6191 N Canfield Ave</h4>
                                <div class="address">
                                	<p class="header">3,6 miles away</p>
                                    <p>
                                    	Labcorp<br />
                                        Chicago, IL 60631<br />
                                        <span class="blue">888-749-6269</span>
                                </div>
                                <div class="hours">
                                	<p class="header">Hours:</p>
                                    <p>
                                    	M-F DRUG SCREENS DRUG SCREENS<br />
                                        7:30am-3:30pm, 7:30am-3:30pm 7:30am-3:30pm<br />
                                        10:00am-5:00pm
                                </div>
                                <a class="btn_orange_25_reflection" href="#">order & test here</a>
                                
                                <div class="clear"></div>
                            </div>
                            
                            <div class="item">
                            	<h4>6191 N Canfield Ave</h4>
                                <div class="address">
                                	<p class="header">3,6 miles away</p>
                                    <p>
                                    	Labcorp<br />
                                        Chicago, IL 60631<br />
                                        <span class="blue">888-749-6269</span>
                                </div>
                                <div class="hours">
                                	<p class="header">Hours:</p>
                                    <p>
                                    	M-F DRUG SCREENS DRUG SCREENS<br />
                                        7:30am-3:30pm, 7:30am-3:30pm 7:30am-3:30pm<br />
                                        10:00am-5:00pm
                                </div>
                                <a class="btn_orange_25_reflection" href="#">order & test here</a>
                                <div class="clear"></div>
                            </div>
                            
                            <div class="item">
                            	<h4>6191 N Canfield Ave</h4>
                                <div class="address">
                                	<p class="header">3,6 miles away</p>
                                    <p>
                                    	Labcorp<br />
                                        Chicago, IL 60631<br />
                                        <span class="blue">888-749-6269</span>
                                </div>
                                <div class="hours">
                                	<p class="header">Hours:</p>
                                    <p>
                                    	M-F DRUG SCREENS DRUG SCREENS<br />
                                        7:30am-3:30pm, 7:30am-3:30pm 7:30am-3:30pm<br />
                                        10:00am-5:00pm
                                </div>
                                <a class="btn_orange_25_reflection" href="#">order & test here</a>
                                <div class="clear"></div>
                            </div>
                            
                        </div> <!-- /std_state_search_results -->
                        
                        <h3>STD Testing Centers By State:</h3>
                        
                        <div class="states_list location_list">
                        	<ul>
                            	<li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                            </ul>
                        </div>
                        
                        <div class="states_list location_list">
                        	<ul>
                            	<li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                            </ul>
                        </div>
                        
                        <div class="states_list location_list">
                        	<ul>
                            	<li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                                <li><a href="#">Alaska STD Testing</a></li>
                            </ul>
                        </div>
                        
                    </div> <!-- /std_testing_state -->
                    
                </div> <!-- /left_col -->
                
                <div id="right_col">
                	Widgets here
                </div> <!-- /right_col -->
                
            </div> <!-- /content -->
            
        <!-- /div> <!-- /.all -->
    <!-- /div> <!-- /.bg_white -->
    
    <!-- div id="footer" class="all">
    	<div id="menu_tests" class="border-right column">
        	<h4>STD Tests</h4>
        	<table>
            	<tr>
                	<td>
                    	<ul>
                        	<li><a href="#">Chlamydia Test </a></li>
                            <li><a href="#">Gonorrhea Test </a></li>
                            <li><a href="#">HIV Test</a></li>
                            <li><a href="#">Syphllis Test</a></li>
                            <li><a href="#">Hepatitis B Test </a></li>
                        </ul>
                    </td>
                    <td>
                    	<ul>
                        	<li><a href="#">Hepatitits C Test </a></li>
                            <li><a href="#">Home Tests </a></li>
                            <li><a href="#">Oral Herpes Test </a></li>
                            <li><a href="#">Genital Herpes Test </a></li>
                            <li><a href="#">Trichomoniasis Test </a></li>
                        </ul>
                    </td>
                </tr>
            </table>
        </div> <!-- /menu_test -->
        <!-- div id="menu_popular" class="border-right column">
        	<h4>Popular Content</h4>
            <ul>
                <li><a href="#">STD Tests & Prices</a></li>
                <li><a href="#">How STD Testing Works</a></li>
                <li><a href="#">Find STD Test Location</a></li>
                <li><a href="#">View STD Test results</a></li>
                <li><a href="#">Blog</a></li>
            </ul>
        </div> <!-- /menu_popular -->
        <!-- div id="menu_pinpoint" class="border-right column">
        	<h4>Meet PinpointMD</h4>
            <ul>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Medical Advisory Board</a></li>
                <li><a href="#">STD Counselors  </a></li>
                <li><a href="#">Terms</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Site Map</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div> <!-- /menu_popular -->
        <!--div id="menu_contact" class="column">
        	<div class="box_dark">
            	<h4>Test for STDs in Complete Privacy</h4>
                <p>Fast, easy, and as accurate as hospital testing.</p>
                <a class="btn_orange" href="#">order now</a>
                <div class="clear"></div>
            </div>
            <h4 class="social">
            	Stay in Touch: 
                <a href="#" target="_blank" class="fb"><img src="images/icon_fb.png" /></a>
                <a href="#" target="_blank" class="twitter"><img src="images/icon_tweeter.png" /></a>
            </h4>
            <div class="address">
            	<div class="left">25 E. Washington St., Ste. 400 </div>
               	<div class="right">Chicago, IL 60610</div>
            </div>
        </div> <!-- /menu_contact -->
        <!--div class="clear"></div>
    </div> <!-- /footer -->
