<?php

	$cities = $this->getCityList();

	$state =  $this->getCurState();

	$stateFull = $this->getCurStateFull();

	$count = count($cities);
	$col = round($count/2);		

	//$states = $this->getStateList();
	$baseDir = Mage::getBaseDir();

?>  

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>

<style>
	body { background: #fff url(http://getstdtested.com/lp/07/images/bg.gif) left top repeat; }
	#header_wrapper { display: none; }

* {
	margin: 0;
	padding: 0;
	border: 0;
}

#all, .all {
    left: 0;
    margin-left: 0;
    position: relative;
    width: 100%;
}

.bg_white { background: transparent; }

.wrap {
	width: 960px;
	height: 100%;
	margin: 0 auto;
}
	
/* Sticky button */

#b-get-tested-sticky {
	position: fixed;
	top: 180px;
	right: 0;
	display: block;
	width: 137px;
	height: 52px;
	margin: 0 auto;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/b-get-tested-sticky.png) left top no-repeat;
}


/* Header */

#header-wrap {
	width: 100%;
	height: 103px;
	background: #fff;
}

#header {
	width: 960px;
	margin: 0 auto;
}

#header #logo {
	float: left;
	width: 310px;
	height: 103px;
	background: transparent url(http://getstdtested.com/lp/07/images/logo.jpg) left center no-repeat;
}

#header #logo a {
	width: 310px;
	height: 103px;
	margin: 0 auto;
	display: block;
	text-indent: -9999px;
}

#header #nav {
	float: right;
	width: 600px;
	padding: 50px 0 0 0;
	color: #919191;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 16px;
	font-weight: normal;
	line-height: 21px;
	text-align: right;
}

#header #nav a {
	color: #717171;
	text-decoration: none;
}

#header #nav a:hover {
	color: #555;
	text-decoration: underline;
}

#header #nav #phone {
	color: #F96D21;
}

#header #nav {
	z-index: 3000;
	width: 620px;
	padding: 18px 0 0 0;
	text-align: left;
}

#header #nav #phone {
	display: block;
	padding-right: 14px;
	text-align: right;
}

#header #nav ul {
	margin: 16px 0 0 0;
	padding: 0;
	list-style: none;
}

#header #nav li {
	display: block;
	width: auto;
	float: left;
	padding: 0;
	list-style: none;
	border-right: 1px solid #77A3BE;
}

#header #nav li.last {
	border: 0;
}

#header #nav a {
	display: block;
	width: auto;
	float: left;
	color: #717171;
	font-weight: normal;
	line-height: 26px;
	padding: 0 12px;
	font-size: 14px;
}

#header #nav li:hover a {
	color: #555;
}

#header #nav .top_submenu {
	z-index: 3000;
	position: absolute;
	margin-top: 26px;
	background: #fff;
	border: 2px solid #113f5b;
	-moz-border-radius: 0 10px 10px 10px;
	border-radius: 0 10px 10px 10px;
	visibility: hidden;
	padding: 15px;
}

#header #nav li:hover .top_submenu {
	visibility: visible;	
}

#header #nav .top_submenu label {
	display: block;
	padding-bottom: 5px;
}

#header #nav .top_submenu .text {
	width: 60px;
	float: left;
	height: 32px;
	margin-right: 10px;
}

#header #nav .top_submenu .submit {
	float: left;
}

#header #nav #submenu-tests ul {
	margin: 0;
}

#header #nav #submenu-tests ul li {
	float: none; 
	border: 0;
}

#header #nav #submenu-tests ul li strong {
	display: block;
	padding: 2px 0 7px 0;
	color: #E77640;
	font-size: 15px;
	font-weight: bold;
}

#header #nav #submenu-tests ul li a {
	float: none; 
	padding: 1px 0 0 0;
	color: #023A4C;
	font-size: 13px;
	line-height: 20px;
	background: none;
}

#header #nav #submenu-tests ul li a:hover {
	color: #E77640;
}


/* Banner */

#banner-wrap {
	width: 100%;
	height: 492px;
	background: #0e6788 url(http://getstdtested.com/lp/07/images/hero-bg.jpg) left top repeat-x;
	overflow: hidden;
}

#hero-image {
	width: 100%;
}

#banner { 
	clear: both;
	display: block;
	width: 960px;
	height: 492px;
	margin: 0 auto;
	padding: 0;
	background: #0e6788 url(http://getstdtested.com/lp/07/images/hero.jpg) left top no-repeat;
}

#banner #banner-heading1 {
	margin: 0;
	padding: 30px 0 0 0;
	color: #fff;
	font-family: 'Open Sans Condensed', arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 50px;
	font-weight: bold;
	font-style: normal;
	line-height: 55px;
	letter-spacing: -1px;
	text-shadow: 1px 2px #1a4c6c;
	background: none; 
}

#banner #banner-heading2 {
	margin: 0 0 0 -3px;
	padding: 0;
	color: #f96d21;
	font-family: 'Open Sans Condensed', arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 95px;
	font-weight: bold;
	font-style: normal;
	line-height: 100px;
	letter-spacing: -3px;
	text-shadow: 1px 2px #f5fcff;
	background: none; 
}

#banner #banner-heading3 {
	margin: 0;
	padding: 0;
	color: #fff;
	font-family: 'Open Sans Condensed', arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 40px;
	font-weight: bold;
	font-style: normal;
	line-height: 60px;
	letter-spacing: -1px;
	text-shadow: 1px 2px #11374f;
	background: none; 
}

#banner ul {
	margin: 35px 0 0 0;
	padding: 0;
	list-style-type: none;
	list-style-image: none;
}

#banner ul li {
	clear: both;
	display: block;
	float: left;
	margin: 0 0 10px 0;
	padding: 14px 25px 14px 18px;
	color: #fff;
	font-size: 23px;
	line-height: 21px;
	list-style-type: none;
	list-style-image: none;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-hero-li.png) left top repeat;
}

#banner ul li span {
	clear: both;
	display: block;
	float: left;
	width: 42px;
	height: 20px;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-hero-arr.png) left center no-repeat;
}

#banner #b-get-tested {
	padding: 50px 0 0 575px;
}

#banner #b-get-tested a {
	width: 365px;
	height: 100px;
	display: block;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/b-schedule-your-test.png) left top no-repeat;
}
	

#content-wrap { width: 950px; margin: 0 auto; }

#intro-content-wrap	{ width: 100%; height: auto; background: #a8d4e4 url(http://getstdtested.com/lp/07/images/bg-how-it-works.jpg) left bottom repeat-x; }

#intro-content-wrap .col2 { float: left; width: 470px; }

#intro-content-wrap h1 { padding-bottom: 0; color: #1e4962; }
#intro-content-wrap h2 { color: #1e4962; }
#intro-content-wrap p { padding-right: 25px; color: #1e4962; }
	

/* How it Works */

#how-it-works-wrap {
	width: 100%;
	height: 250px;
	background: #a8d4e4 url(http://getstdtested.com/lp/07/images/bg-how-it-works.jpg) left bottom repeat-x;
}

#how-it-works {
	width: 960px;
	height: 247px;
	margin: 0 auto;
	padding: 0;
	list-style-type: none;
	list-style-image: none;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-how-it-works-divider.gif) left top repeat-y;
}

#how-it-works li {
	float: left;
	width: 240px;
	height: 247px;
	margin: 0;
	padding: 0;
	font-size: 15px;
	line-height: 20px;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-how-it-works-divider.gif) right top repeat-y;
}

#how-it-works li strong {
	display: block;
	width: 236px;
	height: 85px;
	margin: 0 auto;
	text-indent: -9999px;
}

#how-it-works li#how-it-works-1 strong { background: transparent url(http://getstdtested.com/lp/07/images/how-it-works-icons.jpg) left 17px no-repeat; }
#how-it-works li#how-it-works-2 strong { background: transparent url(http://getstdtested.com/lp/07/images/how-it-works-icons.jpg) -242px 17px no-repeat; }
#how-it-works li#how-it-works-3 strong { background: transparent url(http://getstdtested.com/lp/07/images/how-it-works-icons.jpg) -482px 17px no-repeat; }
#how-it-works li#how-it-works-4 strong { background: transparent url(http://getstdtested.com/lp/07/images/how-it-works-icons.jpg) -726px 17px no-repeat; }

#how-it-works li p {
	padding: 0 20px 5px 20px;
	color: #2b6175;
	font-size: 14px;
	text-align: center;
}


/* Free vs Paid Testing */

#free-heading {
	padding: 25px 0 20px 0;
	color: #1E4962;
	font-size: 28px;
	line-height: 34px;
}

#free-vs-paid {
	float: left;
	width: 660px;
}

#free-vs-paid table {
	margin: 0 0 10px 0;
}

.fvp-table-col-head-1 {
	width: 200px;
	height: 60px;
	padding: 10px 15px;
	color: #fff;
	text-align: center;
	font-size: 20px;
	background: #f6861f url(http://getstdtested.com/skin/frontend/default/getstdtested/images/free-vs-paid-col-heading.gif) left bottom repeat-x;
	border-right: 2px solid #fff;
	border-bottom: 2px solid #ff5e00;
	border-radius: 10px 10px 0 0;
}
.fvp-table-col-head-1 span { font-size: 26px; }

.fvp-table-col-head-2 {
	width: 200px;
	height: 60px;
	padding: 11px 15px 10px 15px;
	color: #ffede1;
	text-align: center;
	font-size: 18px;
	background: #f6861f url(http://getstdtested.com/skin/frontend/default/getstdtested/images/free-vs-paid-col-heading.gif) left bottom repeat-x;
	border-left: 2px solid #fff;
	border-bottom: 2px solid #ff5e00;
	border-radius: 10px 10px 0 0;
}

.fvp-table-col1 { 
	width: 140px;
	padding: 15px 15px 15px 0;
	color: #1b577b;
	font-size: 15px;
	font-weight: bold;
	text-transform: uppercase;
	text-align: right;
	background: #fff url(http://getstdtested.com/skin/frontend/default/getstdtested/images/free-vs-paid-col-left.gif) right top repeat-y;
	border-bottom: 1px solid #fff;
}

.fvp-table-col2 { 
	width: 200px;
	padding: 10px 15px;
	background: transparent;
	color: #1b577b;
	font-family:Arial, Helvetica, sans-serif;
	font-size:12px;
	border-left: 4px solid #ff5e00;
	border-right: 1px solid #ff5e00;
	border-bottom: 1px solid #ff5e00;
}

.fvp-table-col3 {
	width: 200px;
	padding: 10px 15px;
	background: #d8d8d8;
	color: #4c5f63;
	font-family:Arial, Helvetica, sans-serif;
	font-size:12px;
	border-right: 4px solid #ff5e00;
	border-bottom: 1px solid #ff5e00;
}

.fvp-table-col-bottom { border-bottom: 4px solid #ff5e00; }

#locations-box {
	float: right;
	width: 280px;
	background: #fff;
	border: 1px solid #dfdfdf;
	border-radius: 5px 5px 5px 5px;
	box-shadow: 0px 0px 6px #aaaaaa;
}

#locations-header {
	background: #1e6792 url(http://getstdtested.com/skin/frontend/default/getstdtested/images/free-std-clinics-location-bg.gif) left bottom repeat-x;
	border-bottom: 1px solid #bcbcbc;
	border-radius: 5px 5px 0px 0px;
}

#locations-header h3 {
	padding: 15px 20px 14px 20px;
	color: #fff;
	font-size: 21px;
	line-height: 25px;
	text-shadow: 0px 0px #fff;
}

#locations-content {
	padding: 15px 20px 5px 20px;
}

.loc-list-link a { color: #0C6E8E; font-weight:bold; }
.loc-list-link a:hover { text-decoration:underline; }


/* Trustbuilders */

#trustbuilders {
	clear: both;
	width: 960px;
	height: 150px;
	display: block;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/trustbuilders.jpg) left top no-repeat;
}


/* Quote */

.wrap div.quote {
	clear: both;
	display: block;
	width: 717px;
	height: 145px;
	margin: 0 auto 12px auto;
	padding: 18px 0 0 0;
	color: #fff;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 20px;
	font-weight: normal;
	font-style: italic;
	line-height: 28px;
	text-align: center;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-quote.png) left top no-repeat;
}

.wrap div.quote span { color: #a5e8ee; }

.wrap div.quote div {
	padding: 16px 88px 0 0;
	color: #7d8d91;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 16px;
	line-height: 24px;
	font-weight: normal;
	font-style: italic;
	text-align: right;
}


/* Medical Board */

#h-medical-board {
	clear: both;
	display: block;
	width: 960px;
	height: 120px;
	margin: 0;
	padding: 0;
	color: #777;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 20px;
	font-weight: normal;
	line-height: 28px;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/h-medical-board.gif) left 40px no-repeat;
}

.medical-board-col {
	float: left;
	width: 320px;
	height: 410px;
	text-align: center;
	background: transparent url(http://getstdtested.com/lp/07/images/bg-medical-board.jpg) center top no-repeat;
}

.medical-board-col img {
	margin: 42px auto 16px auto;
}

.medical-board-col h4 {
	display: block;
	padding: 2px 38px 8px 38px;
	color: #ea5c08;
	font-size: 15px;
	line-height: 21px;
}

.medical-board-col p {
	padding: 2px 38px 0 38px;
	color: #717171;
	font-size: 14px;
}


/* Get Tested Today Button */

#b-get-tested-today {
	clear: both; 
	display: block;
	width: 400px; 
	height: 120px;
	margin: 0 auto; 
	text-indent: -9999px; 
	background: transparent url(http://getstdtested.com/lp/07/images/b-get-tested-today.jpg) center 25px no-repeat;
}


/* Phone CTA */

.phone-cta-wrap {
	width: 100%;
	height: 113px;
	background: #1f6794 url(http://getstdtested.com/lp/07/images/bg-phone-cta.jpg) left top repeat-x;
}

.phone-cta {
	clear: both; 
	display: block; 
	width: 960px; 
	height: 113px;
	margin: 0 auto;
	padding: 0 185px 0 0;
	color: #f37125;
	font-family: 'Open Sans', arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 56px;
	font-weight: bold;
	font-style: italic;
	line-height: 110px;
	letter-spacing: 1px;
	text-align: right;
	text-shadow: -1px -1px #1a4c6c;
	background: transparent url(http://getstdtested.com/lp/07/images/phone-cta.jpg) center center no-repeat;
	overflow: hidden;
}


/* Product widget */

#h-get-tested-today {
	clear: both;
	display: block;
	width: 218px;
	height: 85px;
	margin: 0;
	padding: 0;
	color: #777;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	font-size: 20px;
	font-weight: normal;
	line-height: 28px;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/h-get-tested-today.gif) left 32px no-repeat;
}

#order {
    font-size: 13px;
	font-family: Arial,Helvetica,sans-serif;
	line-height: 19px;
}

#order h1, #order h2, #order h3, #order h4 {	
	text-shadow: 0 0 #fff;
}

#order h2 {
	font-size: 22px;
    line-height: 30px;
    padding: 16px 45px 10px 45px;
    color: #1f6794;
    font-family: arial,tahoma,verdana,helvetica,sans-serif;
    text-shadow: 1px 1px #FFFFFF;	
	background: none;
}

#order h2.first {
	float: left;
	padding-right: 25px;
}

#order h2.first strong {
    color: #1f6794;
}

#order #location_results h3 {
	padding-left: 45px;
	padding-right: 45px;
    font-size: 13px;
	font-family: Arial,Helvetica,sans-serif;
	line-height: 19px;
}

#order h4 {
	font-family: Tahoma, Geneva, sans-serif;
	font-size: 14px;
	color: #333;
	margin: 0;
	padding: 0;
	font-weight: normal;
}

#order #ultimate_package h4 strong {
	font-size: 18px;
	color: #E97640;
}

#order ul {
	padding: 15px 0 0 0;
}

#order ul li {
	padding: 0 0 6px 0;
}

#order input.text, #order input.input-text {
    border: 1px solid #D6D6D6;
    color: #7A7A7A;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 16px;
    padding: 0 7px;
}

#order #location_form {
	padding: 8px 0 0 0;	
	overflow: hidden;
}

#order #location_form .text {
	font-weight: bold;
	width: 80px;
	height: 32px;
	margin-right: 10px;
	padding: 0 9px;
}

#order #location_form .b-submit {
	display: inline-block;
	width: 93px;
	height: 32px;
    padding: 0 15px;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/b-submit.gif) left top repeat;
	cursor: pointer;
}

#order p {
	margin: 0;
	padding: 2px 45px 16px 45px;
}

.btn_orange {
	background: #e97640;
	color: #fff;
	font-weight: bold;
	font-family: Tahoma, Geneva, sans-serif;
	text-align: center;
	display: block;
	width: auto;
	padding: 10px 20px;
	height: 20px;
	text-transform: uppercase;
	-moz-border-radius: 10px;
 	border-radius: 10px;
 	font-size: 16px;
}

.btn_orange:hover {
	background: #fe8e59;
}

.btn_orange_reflection {
	display: block;
	width: 224px;
	height: 20px;
	padding: 13px 0px 12px 0px;
	font-size: 17px;
	font-weight: bold;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
	background: url(http://getstdtested.com/media/images/btn_orange_reflection.png) center center no-repeat;
	-moz-border-radius: 10px;
 	border-radius: 10px;
	cursor:pointer;
}

.btn_orange_reflection:hover {
	opacity:0.8;
	filter:alpha(opacity=80);
	cursor:pointer;
}

input.btn_orange_reflection {
	height: 45px;
	cursor:pointer;
}

.btn_orange_32_reflection {
	display: block;
	width: auto;
	height: 18px;
	padding: 7px 0px;
	font-size: 13px;
	font-weight: bold;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
	background: url(http://getstdtested.com/media/images/btn_orange_32_reflection.png) center center no-repeat;
	-moz-border-radius: 5px;
 	border-radius: 5px;
}

input.btn_orange_32_reflection {
	height: 32px;
	border: none;
	padding: 0px 15px;
	cursor: pointer;
	width: auto;
}

.btn_orange_25_reflection {
	display: block;
	width: auto;
	height: 13px;
	padding: 6px 10px;
	font-size: 10px;
	font-weight: bold;
	color: #fff;
	text-align: center;
	text-transform: uppercase;
	background: url(http://getstdtested.com/media/images/btn_orange_25_reflection.png) center center no-repeat;
	-moz-border-radius: 5px;
 	border-radius: 5px;	
}

.btn_orange_25_reflection:hover {
	opacity:0.8;
	filter:alpha(opacity=80);	
}

.btn_orange_shadow {
	display: block;
	width: 340px;
	height: 67px;
	padding-top: 30px;
	background: url(http://getstdtested.com/media/images/btn_orange_shadow.png) center center no-repeat;
	text-align: center;
	font-size: 29px;
	font-weight: bold;
	color: #fff;
	text-shadow: #ae3a04 2px 2px 1px;	
}

.btn_orange_shadow:hover {
	opacity:0.8;
	filter:alpha(opacity=80);	
}

.btn_blue_reflection {
	-moz-border-radius: 5px;
 	border-radius: 5px;
	font-size: 15px;
	font-weight: bold;
	color: #fff;
	text-transform: uppercase;
	width: 156px;
	height: 23px;
	display: block;
	padding-top: 7px;
	text-align: center;
	border: none;
	background: url(http://getstdtested.com/media/images/btn_blue_reflection.png) center center no-repeat;
}

.btn_blue_reflection:hover {
	opacity:0.8;
	filter:alpha(opacity=80);
	text-decoration: none;
}

input.submit {
	border: none;
	padding: 0px 15px;
	cursor: pointer;
	width: auto;
}

input.submit:hover {
	opacity:0.8;
	filter:alpha(opacity=80);
	text-decoration: none;
}

button.submit {
	border: none;
	padding: 0px 15px;
	cursor: pointer;
	width: auto;
}


.first {
	float: left;
	/*width: 508px;*/
	padding-top: 12px;
}

#your-zip-code {
	float: left;
	width: 300px;
	height: 55px;
	margin: 0;
	padding: 22px 0 0 0;
	color: #005f7e;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 14px;
	font-weight: bold;
}

#your-zip-code #location_form {
	padding: 2px 0 0 0;
	overflow: hidden;
}

#your-zip-code #location_form .text {
	width: 118px;
	height:	30px;
	margin: 3px 0 0 0;
	padding: 0 3px 0 4px;
    color: #7A7A7A;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 16px;
	font-weight: bold;
	border: 1px solid #999;
}

#your-zip-code #location_form .submit {
	display: inline-block;
}

#order #location_results {
	margin: 0;
	padding: 0;
}

#order_module2 {
	clear: both;
	width: 935px;
	margin-left: 25px;
	height: 415px;
	background: transparent url(http://getstdtested.com/lp/07/images/order-widget-bg.png) left 35px no-repeat;
}

#order_module2 #orderWidget {
	margin: -20px 0 0 0;
}

#order_module2 #at_home {
	width: 255px;
	height: 375px;
	float: left;
	overflow: hidden;
}

#order_module2 #at_home .header {
	width: 255px;
	height: 134px;
	display: block;
	text-indent: -9999px;
}

#order_module2 #at_home .content {
	padding: 10px 0 0 26px;
}

#order_module2 #at_home ul {
	margin: 0;
	padding: 0;
	list-style: none;
}

#order_module2 #at_home li {
	float: left;
	display: block;
	width: 170px;
	padding-bottom: 8px;
	color: #5c5c5c;
	font-size: 13px;
	line-height: 18px;
	list-style: none;
}

#order_module2 #at_home li input {
	margin: 0 8px 0 0;
	padding: 0;
}

#order_module2 #at_home li.price {
	float: right;
	width: 50px;
	padding-top: 1px;
	color: #e75716;
	font-size: 13px;
	font-weight: bold;
	line-height: 18px;
}

#order_module2 #lab_package {
	width: 218px;
	height: 375px;
	float: left;
	overflow: hidden;
}

#order_module2 #lab_package .header {
	width: 218px;
	height: 109px;
	display: block;
	text-indent: -9999px;
}

#order_module2 #lab_package .content {
	height: 216px;
	padding: 12px 0 0 47px;
}

#order_module2 #lab_package ul {
	margin: 0;
	padding: 0;
	list-style: none;
}

#order_module2 #lab_package li {
	float: left;
	display: block;
	width: 170px;
	padding: 0 0 8px 26px;
	color: #005f7e;
	font-size: 13px;
	font-weight: bold;
	line-height: 16px;
	background: transparent url(http://getstdtested.com/lp/07/images/order-widget-checkmark.png) left 2px no-repeat;
}

#order_module2 #lab_package li.price {
	float: right;
	width: 50px;
	padding-top: 1px;
	color: #e75716;
	font-size: 13px;
	font-weight: bold;
}

#order_module2 #lab_packapge_footer {
}

#order_module2 #lab_packapge_footer .price {
	float: left;
	display: block;
	width: 76px;
	text-indent: -9999px;
}

#order_module2 #lab_packapge_footer input#expert_package {
	display: block;
	float: left;
	width: 25px;
	height: 20px;
	margin-top: 0;
}

#order_module2 #lab_packapge_footer label {
	float: left;
	display: block;
	width: 90px;
	height: 18px;
	text-indent: -9999px;
	cursor: pointer;
}

#order_module2 #lab_tests1 {
	width: 255px;
	height: 375px;
	float: left;
	overflow: hidden;
}

#order_module2 #lab_tests1 .header {
	width: 255px;
	height: 134px;
	display: block;
	text-indent: -9999px;
}

#order_module2 #lab_tests1 .content {
	padding: 10px 0 0 26px;
}

#order_module2 #lab_tests1 ul {
	margin: 0;
	padding: 0;
	list-style: none;
}

#order_module2 #lab_tests1 li {
	float: left;
	display: block;
	width: 170px;
	padding-bottom: 7px;
	color: #5c5c5c;
	font-size: 13px;
	line-height: 18px;
	list-style: none;
}

#order_module2 #lab_tests1 li input {
	margin: 0 8px 0 0;
	padding: 0;
}

#order_module2 #lab_tests1 li.price {
	float: right;
	width: 50px;
	color: #e75716;
	font-size: 13px;
	font-weight: bold;
	line-height: 18px;
}

#order_module2 #your_order {
	float: right;
	width: 160px;
	height: 375px;
	text-align: right;
	border: 0;
}

#order_module2 .your_order_side {
	width: 100% !important;
}

#order_module2 #your_order .total {
	padding: 262px 35px 6px 0;
	color: #023a4c;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 17px;
	font-weight: bold;	
	letter-spacing: -1px;
}

#order_module2 #your_order #total_price {
	padding: 4px 0 18px 0;
	color: #e86b2c;
	font-size: 19px;
	font-weight: bold;
	text-align: right;
	display: block;
}

#order_module2 #your_order .submit {
	clear: both;
	margin: 0;
}


#trustbuilders2 {
	clear: both;
	width: 960px;
	height: 180px;
	display: block;
	text-indent: -9999px;
	background: transparent url(http://getstdtested.com/lp/07/images/trustbuilders.jpg) left 28px no-repeat;
}


/* Content */

h1, h2, h3, h4 {
	padding: 12px 0 6px 0;
	color: #4f4f4f;
	font-family: arial, tahoma, verdana, helvetica, sans-serif;
	text-shadow: 1px 1px #fff;
}

h1 {	
	padding: 18px 0 10px 0;
	font-size: 27px;
}

h2 {	
	padding: 10px 0 10px 0;
	font-size: 23px;
	line-height: 30px;
}
h2 span { color: #e97640; }

h3 {
	padding: 8px 0 10px 0;
	font-size: 24px; 
	line-height: 32px;
}

h4 {
	padding: 12px 0 10px 0;
	font-size: 18px;
}

p {
	margin: 0;
	padding: 2px 0 16px 0;
}

a {
	color: #0b6d91;
	text-decoration: none;
}

a:hover {
	color: #0b6d91;
	text-decoration: underline;
}

a:active, a:focus {
	outline: none;
}

small {
	color: #777;
	font-size: 11px;
	line-height: 16px;
	margin: 0;
}

ul {
	margin: 0;
	padding: 4px 25px 12px 65px;
	list-style-type: disc;
	list-style-image: none;
}

ol {
	margin: 0;
	padding: 4px 25px 12px 65px;
}

li {
	padding: 0 0 6px 0;
}

strong {
	color: #555;
}


/* Toolbox */

.aleft { text-align: left; }
.acenter { text-align: center; }
.aright { text-align: right; }

.fleft { float: left; }
.fright { float: right; }

.cboth { clear: both; }
.cleft { clear: left; }
.cright { clear: right; }


	#news-feeds { clear: both; width: 100%; margin: 0 auto; text-shadow: 0px 0px #fff; background: #1f6794 url(http://getstdtested.com/lp/07/images/footer-bg.jpg) left top repeat-x; }
	.news-tweets {
		float: left; 
		width: 475px;
		margin: 5px 0 0 0;
		text-shadow: 0px 0px #fff;
	}
	.news-tweets h3 {
		padding: 15px 25px 5px 0;
		color: #fff;
		font-size: 16px;
		line-height: 22px;
		text-shadow: 0px 0px #fff;
	}
	.news-tweets li {
		padding-right: 25px;
		color: #BFE2FF;
		font-size: 12px;
	}
	.news-tweets li.news {
		margin: 4px 0 2px 0;
	}
	.news-tweets li.alt1 {
		background: transparent;
	}

	#footer-guarantee-wrap { background-color: #1f6794; }
	#footer-guarantee { background: transparent url("/skin/frontend/default/getstdtested/images/footer-guarantee-badge.png") left bottom no-repeat; }

	#footer { width: 100%; text-shadow: 0px 0px #fff; background: #1f6794; }
	#footer #footer-wrap { width: 960px; margin: 0 auto; }
	#footer h4 { text-shadow: 0px 0px #fff; }
</style>


<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
	
	if (document.getElementById('zip_code').value.length != 5 ||is_int(document.getElementById('zip_code').value) === false) {			
	//if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder",array('_secure'=>false)) ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;

var ultimatePackage = 229;

var indiSkuArr = new Array();
	indiSkuArr[0] = 'hiv-lab';
	indiSkuArr[1] = 'chlamydia-gonorrhea-lab';
	indiSkuArr[2] = 'oral-genital-herpes-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'hepatitis-b-lab';
	indiSkuArr[5] = 'hepatitis-c-lab';
	indiSkuArr[6] = 'hiv-early-detection-lab';

var indiTestOrig = new Array();
	indiTestOrig[0] = 79;
	indiTestOrig[1] = 149;
	indiTestOrig[2] = 149;
	indiTestOrig[3] = 89;
	indiTestOrig[4] = 89;
	indiTestOrig[5] = 89;
	indiTestOrig[6] = 179;
	
	var homeSkuArr = new Array();
	homeSkuArr[0] = 'hiv-home';
	homeSkuArr[1] = 'chlamydia-gonorrhea-home';
	homeSkuArr[2] = 'trichomoniasis-home';
	
var homeTestOrig = new Array();
	homeTestOrig[0] = 99;
	homeTestOrig[1] = 149;
	homeTestOrig[2] = 199;
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		if (document.getElementById('hiv-early-detection-lab').checked == false) {
	
			total = 0;
			
			price = 0;
			
			cartArr = new Array();
		
		} else {
		
			total = 0;
		
			price = indiTestOrig[6];
				
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
		
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = parseInt(document.getElementById(el).value) + price;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 99;
    			
    			}
			}
	   	
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true && document.getElementById('hiv-early-detection-lab').checked == true) {
	
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('hiv-early-detection-lab').checked = false;
			
			document.getElementById('hiv-early-detection-lab').value = indiTestOrig[6];
			
			document.getElementById('package').value = "";
			
			total = 0;
		
		}
		
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
			
		}
		
		/*
if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').value < 0) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
		
		}
*/
		
	
		
		
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
			
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		
		if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').checked == false) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
			
			total = total + price;
		
		} else {
		
		total = total + price;
		
		}
		
			
	   	
	   	   
	
	   document.getElementById('widget_total').innerHTML = '$'+(total);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'expert_package') {
		
		//document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			//document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			//document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	
	//document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	/*
if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
*/
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>


<?php // PAP Header Tracking

if(isset($_GET['a_aid'])){ $_SESSION['a_aid'] = $_GET['a_aid']; } else { $_SESSION['a_aid'] = 0; }

if($_SESSION['a_aid']) { //create div for tracking
		
	$config  = Mage::getConfig()->getResourceConnectionConfig("default_setup");

	$db = new PDO ('mysql:dbname='.$config->dbname.';host='.$config->host, $config->username, $config->password);

	$affiliate_exists = false;
	
	Mage::getSingleton('core/session')->setAffiliateId($_SESSION['a_aid']);
	Mage::getSingleton('core/session')->setPpmdAffiliate($_SESSION['a_aid']);
	
	$q = 'select phone from affiliates where referral_id = "'.$_SESSION['a_aid'].'";';
	
		$sth = $db->prepare($q);
		$sth->setFetchMode(Zend_Db::FETCH_ASSOC);
    	$sth->execute();  
    		
    	$res = $sth->fetchAll();
    	
    	$sth = "";
    	        	    	
    $phone = $res[0]['phone'];

	if ($phone != ''){
				
			$phone = str_replace("-","",$phone);
			$phone = str_replace(".","",$phone);
			$phone = str_replace(" ","",$phone);
			
			$p1 = substr($phone,0,3);
			$p2 = substr($phone,3,3);
			$p3 = substr($phone,6,4);

			$phone = $p1."-".$p2."-".$p3;

		?>
		
		<div id="affiliate" style="display:none;">
			<div class="promoNumber">
				<?php echo $phone; ?>
			</div>
		</div>
		
		<?php
		
	} else {
	
		$phone = "866-749-6269";
	
	}	
	
}

// END PAP Header Tracking

?>


<a href="#get-tested" id="b-get-tested-sticky">Get Tested</a>

<div id="header-wrap">
	<div id="header">
		<div id="logo"><a href="http://getstdtested.com/" title="Home | Get STD Tested">Get STD Tested</a></div>
		<div id="nav">
			<span id="phone">Call 866-749-6269</span>
			<ul>
                <li><a href="/std-tests" title="STD Tests">STD Tests</a>
                	<div class="top_submenu" id="submenu-tests">
						<ul>
							<li><strong>Popular Tests Package</strong></li>
							<li><a href="/complete-std-test-package-information" title="Complete STD Test Package">Complete STD Test Package</a></li>
						</ul>
						<ul style="float: left;">
							<li><br /><strong>Individual Tests</strong></li>
							<li><a href="/chlamydia-test-information" title="Chlamydia Test">Chlamydia Test</a></li>
							<li><a href="/gonorrhea-test-information" title="Gonorrhea Test">Gonorrhea Test</a></li>
							<li><a href="/hiv-test-information" title="HIV Test">HIV Test</a></li>
							<li><a href="/hepatitis-b-test-information" title="Hepatitis B Test">Hepatitis B Test</a></li>
							<li><a href="/hepatitis-c-test-information" title="Hepatitis C Test">Hepatitis C Test</a></li>
						</ul>
						<ul style="float: left;">
							<li><br /><strong>&nbsp;</strong></li>
							<li><a href="/oral-herpes-test-information" title="Oral Herpes Test">Oral Herpes Test</a></li>
							<li><a href="/genital-herpes-test-information" title="Genital Herpes Test">Genital Herpes Test</a></li>
							<li><a href="/lp/trichomoniasis-test-information-var1" title="Trichomoniasis Test">Trichomoniasis Test</a></li>
							<li><a href="/syphilis-test-information" title="Syphilis Test">Syphllis Test</a></li>
						</ul>
                    </div>
				</li>
                <li><a href="/how-std-testing-works" title="How It Works">How It Works</a></li>
                <li><a href="/at-home-std-tests" title="Home STD Testing">Home STD Testing</a></li>
                <li><a href="/lab-std-testing" title="Lab STD Testing">Lab STD Testing</a></li>
                <li><a href="/blog" title="Blog">Blog</a></li>
                <li class="last"><a href="/sample-results" title="My Results">My Results</a></li>
            </ul>
		</div>
	</div>
</div>

<script type="text/javascript">	
	p = '<?php echo $phone; ?>';
	
	if (p.length > 6) {	
		document.getElementById('phone').innerHTML = 'Call <?php echo $phone; ?>';
	}	
</script>

<div id="banner-wrap">
	<div id="banner">
		<div id="banner-heading1">Concerned about STDs?</div>
		<div id="banner-heading2">Get Peace of Mind</div>
		<div id="banner-heading3">Test today and get answers fast!</div>
		<ul>
			<li><span></span>100% Confidential STD Testing</li>
			<li><span></span>Highest Quality and Accurate Testing</li>
			<li><span></span>Treatment Available in Most Cases</li>
		</ul>
		<div id="b-get-tested"><a href="#get-tested" title="Schedule Your Test">Schedule Your Test</a></div>
	</div>
</div>

<div id="intro-content-wrap">
	<div class="wrap">
		<h1>Potential Free STD Clinics and<br />Free STD Testing Centers in <?php echo ucwords($stateFull);?></h1>
		<h2>Search our directory of potentially free std testing clinics in <?php echo ucwords($stateFull);?></h2>
		<div class="col2">
			<p>You have reached our database of free std clinics in <?php echo  ucwords($stateFull);?>. Please take the time to browse locations near you. As an individual looking for free STD testing in <?php echo  ucwords($stateFull);?>, please remember that not all of these locations provide comprehensive testing. In fact, many locations may not be able to test and treat your condition at all. Please take the time to review our site and contact these facilities to confirm that they can test you for all STDs within a reasonable amount of time.</p>
		</div>
		<div class="col2">
			<p>If you can't find a free std clinic in <?php echo  ucwords($stateFull);?> among our database of std clinics, then you may find the services of getSTDtested to be a convenient, fast, and pinpoint accurate alternative to your other <?php echo  ucwords($stateFull);?> STD Clinics. getSTDtested.com std clinics can test for nearly every STD including HIV, Chlamydia, Gonorrhea, Herpes, Syphilis, Hepatitis B, Hepatitis C, and Trichomoniasis.</p>
		</div>
	</div>
	<div class="cboth"><br /></div>
</div>

<div class="cboth"></div>

<div class="wrap">

	<h2 id="free-heading">Potential Free STD Clinics &amp; Testing Centers in <?php echo ucwords($stateFull);?></h2>

	<!-- start dynamic pages -->
	<div class="cities_list location_list">
		<ul>
		<?php                        
    		$x = 0;  
    		foreach ($cities as $city) {
    	?>          
			<li>
			<a href="/free-std-clinics/<?php echo str_replace(" ","-",strtolower($city->getData('stateFull')))."-".strtolower($city->getState());?>/<?php echo str_replace(" ","-",strtolower($city->getCity()));?>"><?php echo ucwords(strtolower($city->getCity())).", ".$city->getState();?> STD Testing Centers</a></li>
		<?php 
			if ($x == $col-1) {
		?>
		</ul>
	</div>
	<div class="cities_list location_list">
		<ul>
		<?php
			}
		$x++;
			}
		?>
		</ul>
	</div>
	<!-- end dynamic pages -->

	<div class="cboth"></div>

	<div id="trustbuilders">
		<p>Trusted by customers, the FDA and the sexual community</p>
		<p>Average Customer Review &ndash; <strong>4.5 out of 5 Stars</strong></p>
	</div>
	
	<div class="quote">
		<p>My doctor wouldn't have been able to see me for 2 months.<br />I was able to get <span>same day testing</span> through getSTDtested.com, and<br />my test results came back sooner than 3 days.</p>
		<div>- Male, 36 from Illinois</div>
	</div>
	
</div>

<div class="cboth"><br /></div>

<a name="how"></a>
<div id="how-it-works-wrap">
	<ul id="how-it-works">
		<li id="how-it-works-1">
			<strong>1. ORDER</strong>
			<p>Select which STDs you would like to test for and whether you'd prefer to test at home or at one of 4,000 convenient lab locations. We accept confidential payment via credit and debit cards and e-checks.</p>
		</li>
		<li id="how-it-works-2">
			<strong>2. TEST</strong>
			<p>Visit the lab of your choice. Or, test from the comfort of your home with an at-home STD test kit and send sample to the lab. All testing is performed via blood or urine &ndash; no painful swabbing.</p>
		</li>
		<li id="how-it-works-3">
			<strong>3. RESULTS</strong>
			<p>Your test results will be ready within 3 to 5 days&ndash;faster than a&nbsp;doctor's office. You'll be notified as soon as they are available, and results can be viewed online or discussed over the phone.</p>
		</li>
		<li id="how-it-works-4">
			<strong>4. OPTIONS</strong>
			<p>If the news isn't good, you still have options. Discuss your test with our in-house physicians to help interpret test results and answer questions. From medication to antibiotics, get private treatment.</p></p>
		</li>
	</ul>
	<div class="cboth"></div>
</div>

<div class="wrap">
	
	<h2 id="h-medical-board">Meet Our Medical Advisory Board &ndash; STD testing and treatment endorsed by industry-leading medical professionals</h2>
	
	<div class="medical-board-col">
		<img src="http://getstdtested.com/lp/07/images/medical-board-photo-1.jpg" width="222" height="146" border="0" alt="" />
		<h4>H. Hunter Handsfield, MD</h4>
		<p>With over 30+ years of experience and 250 publications under his belt, Dr.&nbsp;Handsfield has played an integral role in developing modern day STD prevention strategies.</p>
	</div>
	
	<div class="medical-board-col">
		<img src="http://getstdtested.com/lp/07/images/medical-board-photo-2.jpg" width="222" height="146" border="0" alt="" />
		<h4>Barbara Van Der Pol, PhD, MPH</h4>
		<p>Dr. Van Der Pol is a leading advisor for the Centers for Disease Control (CDC) and the National Chlamydia Coalition, performing cutting-edge STD&nbsp;research.</p>
	</div>
	
	<div class="medical-board-col">
		<img src="http://getstdtested.com/lp/07/images/medical-board-photo-3.jpg" width="222" height="146" border="0" alt="" />
		<h4>Neil S. Skolnik, MD</h4>
		<p>Dr. Skolnik is a well-known presenter and recent recipient of the "Top Doctor" Award in Family Medicine by Philadelphia Magazine, regularly contributing to CDC editorial.</p>
	</div>

	<div class="cboth"><br /><br /></div>

</div>

<div class="phone-cta-wrap">
	<div class="phone-cta" id="phoneCTA">866-749-6269</div>
</div>

<script type="text/javascript">	
	p = '<?php echo $phone; ?>';
	
	if (p.length > 6) {
		document.getElementById('phoneCTA').innerHTML = '<?php echo $phone; ?>';
	}	
</script>
		
<div class="wrap">

		<a name="get-tested"></a>
		<h2 id="h-get-tested-today">Get Tested Today</h2>

		<div id="order">
				<div style="clear:both;"></div>
		
                    <div id="order_module2">
					
                    	<form name="orderWidget" id="orderWidget" method="post" action="http://getstdtested.com/customroute/index/checkout">

                            <div id="at_home">
                                <div class="header">At-Home Testing</div>
                                <div class="content">
                                    <ul>
                                        <li><input type="checkbox" value="105.0000" id="hiv-home" onClick="updateWidgetTotal(this.id,4);toggleCartElement(this.id);" name="homeTest[hiv-home]" /><label for="hiv-home">HIV Standard</label></li>
										<li class="price">$105</li>
                                    	<li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<?php } ?> type="checkbox" value="165.0000" id="chlamydia-gonorrhea-home" onClick="updateWidgetTotal(this.id,44);toggleCartElement(this.id);" name="homeTest[chlamydia-gonorrhea-home]" /><label for="chlamydia-gonorrhea-home">Chlamydia &amp; Gonorrhea</label></li>
										<li class="price">$165</li>
                                        <li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<?php } ?> type="checkbox" value="205.0000" id="trichomoniasis-home" onClick="updateWidgetTotal(this.id,3);toggleCartElement(this.id);" name="homeTest[trichomoniasis-home]" /><label for="trichomoniasis-home">Trichomoniasis</label></li>
										<li class="price">$205</li>
                                    </ul>
                                </div>
                            </div>

                            <div id="lab_package">
                                <div class="header">Complete Lab Testing Package</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li>HIV Standard</li>
                                        <li>Chlamydia</li>
                                        <li>Gonorrhea</li>
                                        <li>Oral Herpes</li>
                                        <li>Genital Herpes</li>
                                        <li>Syphilis</li>
                                        <li>Hepatitis B</li>
                                        <li>Hepatitis C</li>
                                    </ul>
									<div style="clear: both;"></div>
                                </div>
								<div id="lab_packapge_footer">
									<span class="price">$229</span>
									<input type="radio" id="expert_package" value="229" onClick="updateWidgetTotal(this.id,14);toggleCartElement(this.id);" name="testPackage" />
									<label for="expert_package">ADD TO CART</label>
									<input id="expert_package_hidden" type="hidden" name="pack_14" value="229">
									<div style="clear: both;"></div>
								</div>
                            </div>

                            <div id="lab_tests1">
                                <div class="header">Lab Testing</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li><input type="checkbox" value="79.0000" id="hiv-lab" onClick="updateWidgetTotal(this.id,11);toggleCartElement(this.id);" name="indiTest[hiv-lab]" /><label for="hiv-lab">HIV Standard</label></li>
										<li class="price">$79</li>
                                        <li><input type="checkbox" value="149.0000" id="chlamydia-gonorrhea-lab" onClick="updateWidgetTotal(this.id,40);toggleCartElement(this.id);" name="indiTest[chlamydia-gonorrhea-lab]" /><label for="chlamydia-gonorrhea-lab">Chlamydia &amp; Gonorrhea</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="149.0000" id="oral-genital-herpes-lab" onClick="updateWidgetTotal(this.id,42);toggleCartElement(this.id);" name="indiTest[oral-genital-herpes-lab]" /><label for="oral-genital-herpes-lab">Oral &amp; Genital Herpes</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="89.0000" id="syphilis-lab" onClick="updateWidgetTotal(this.id,12);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" /><label for="syphilis-lab">Syphilis</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,7);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" /><label for="hepatitis-b-lab">Hepatitis B</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,8);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" /><label for="hepatitis-c-lab">Hepatitis C</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" <?php if (Mage::getSingleton('core/session')->getLabType() == 119) { ?> disabled="disabled" <?php } ?> value="179.0000" id="hiv-early-detection-lab" onClick="updateWidgetTotal(this.id,13);toggleCartElement(this.id);" name="indiTest[hiv-early-detection-lab]" /><label for="hiv-early-detection-lab">HIV Early Detection *</label></li>
										<li class="price">$179</li>
                                    </ul>
                                </div>
                            </div>

							<div id="your_order">                                    
                                <div class="total">
                                	ORDER TOTAL<br />
                                    <span id="total_price"><div id="widget_total">$0</div></span>
                                </div>
                                <input type="button" onclick="checkEmpty();" class="submit btn_orange_32_reflection" value="continue" style="width: 125px;" />
                            </div>
							
							<input type="hidden" id="package" name="package" value="">  							
							
						</form>
						<div id="expert_package-cart" style="display:none;"></div>
					</div>
		
			<div id="trustbuilders2">
				<p>Trusted by customers, the FDA and the sexual community</p>
				<p>Average Customer Review &ndash; <strong>4.5 out of 5 Stars</strong></p>
			</div>
				
		</div>
		<div class="cboth"><br /></div>
	
	</div>
</div>

<div id="news-feeds">
	<div class="wrap">
		<div class="news-tweets">
			<?php 
			//$url = 'http://news.google.com/news?pz=1&cf=all&ned=us&hl=en&as_scoring=r&geo=60614&as_maxm=5&q=transmitted+diseases+stds+OR+hiv+OR+syphilis+OR+chlamydia+OR+gonorrhea+OR+herpes+OR+hepatitis+OR+sexually&as_qdr=a&as_drrb=q&as_mind=19&as_minm=4&cf=all&as_maxd=19&output=rss';
			$url = 'http://news.search.yahoo.com/rss?ei=UTF-8&va_vt=any&vo=std+hiv+herpes+syphilis+chlamydia+gonorrhea+hepatitis&vo_vt=any&ve_vt=any&vp_vt=any&fl=1&vl=lang_en&smonth=11&emonth=12&sday=8&eday=8&catfilt=1';
			$url2 = 'http://news.search.yahoo.com/rss?ei=UTF-8&va_vt=any&vo=std+hiv+herpes+syphilis+chlamydia+gonorrhea+hepatitis&vo_vt=any&ve_vt=any&vp_vt=any&fl=1&vl=lang_en&smonth=11&emonth=12&sday=8&eday=8&catfilt=1';
			include_once $baseDir.'/rss/rss-news.php';
			?>
		</div>

		<div class="news-tweets">
			<?php
			//$url = 'http://search.twitter.com/search.atom?q=stds&rpp=5';
			$url = 'http://api.twitter.com/1/getSTDtested/lists/sex-and-sexual-health/statuses.atom';
			include_once $baseDir.'/rss/rss-twitter.php';
			?>
		</div>
		<div class="cboth"><br /></div>
	</div>
</div>
<div class="cboth"></div>
