<?php
$localepage = Mage::registry('localepage');
	
	$values = unserialize($localepage->getValues());
	
?>        
            <div class="clear"></div>
            <div class="sep10"></div>
            	
            <div id="content">
				<div id="lp_symptoms">
                	<div class="box_navy_bg" id="lp_symptoms_header">
                    	<h1><?php echo $values['h1'];?></h1>
                        <h2><?php echo $values['h2'];?></h2>
                        <div class="question">
                        	<p><?php echo $values['subheading'];?></b></p>
                        </div>
                        <div class="link">
                        	<a href="/std-testing-options" class="btn_orange_shadow">Get Tested Today</a>
                        </div>
                        <div class="clear"></div>
                    </div> <!-- /lp_symptoms_header -->
                    
                    <div id="lp_symptoms_content">
                    	<div class="col_left">
                        	<h3><?php echo $values['h3'];?></h3>
                            <p><?php echo $values['body_content'];?></p>
                        </div> <!-- /.col_left -->
                        
                        <div class="col_right">
                        
                        	<div id="benefits_widget">
                            	<h3><b>Benefits of</b> <br />Private STD Testing</h3>
                                <ul>
                                	<li><span class="orange">Test Today:</span> No wait. Order and test for STDs today. Get results within 3 days through confidential online patient portal.</li>
                                    <li><span class="orange">Highest Accuracy Available:</span> Same trusted labs used by doctors and hospitals nationwide. </li>
                                    <li><span class="orange">Free Physician Consult:</span> Get the facts about STDs through a complimentary consultation with an in-house physician. </li>
                                    <li><span class="orange">Convenient:</span> STD testing available at-home and at 4,000+ nationwide testing centers.</li>
                                    <li><span class="orange">Confidential:</span> No insurance records. STD test results are private.</li>
                                </ul>
                            </div> <!-- /benefits_widget -->
                            
                            <div id="trusted_widget" class="box_grey_border">
                            	<h4><span class="orange">trusted</span> by our customers and <br />the sexual health community</h4>
                                <img src="/media/images/trusted_logos_side_2.png" />
                                <h4><span class="orange">4.5/5</span> star customer reviews</h4>
                                <img src="/media/images/reviews_stars_transp.png" />    
                            </div> <!-- /trusted_widget -->
                        </div> <!-- /.col_right -->
                        
                        <div class="clear"></div>
                        
                    </div> <!-- /lp_symptoms_content -->
                    
                </div> <!-- /lp_symptoms -->
            </div> <!-- /content -->

