<?php 

$_locations = $this->getLabsByZip();

$x = 0;

if ((!is_array($_locations) || !count($_locations)) && !is_object($_locations)) {
		echo "<h3>We apologize - it appears your zip code is invalid or there are no testing locations within 100 miles.  
		Call 866-749-6269 and we'll help determine the best private option for testing.  
		Alternately, click 'ORDER NOW' to order at home STD testing.</h3>";
} else {
	foreach ($_locations as $location) {
	    $labId = $location['id'];
        if ($x < 6) {
        ?>
            <div class="ow_item">
                <h4>Exact address displayed after test selection</h4>
                <div class="location">
                    <p><?php echo ucwords(strtolower($location['name']));?></p>
                    <?php echo ucwords(strtolower($location['city']));?>, <?php echo $location['state'];?> <?php echo $location['zip'];?><br /><span class="blue">866-749-6269</span></p>
                </div>
                <div class="hours">
                    <p class="header">Hours</p>
                    <p><?php echo ucwords(strtolower(str_ireplace("|Sa","<br>Sa",$location['hours'])));?></p>
                </div>
                <input type="radio" name="orderLab" value="">
            </div>
<?php
        $x++;
        }
	}
}
?>
