<?php

$this->resetCart();

$_products = $this->getProducts();

?>
<script type="text/javascript">

var ultimatePackage = 249;

var indiTestOrig = new Array();
	indiTestOrig[0] = <?php echo round($_products['chlamydia-lab']['price']);?>;
	indiTestOrig[1] = <?php echo round($_products['gonorrhea-lab']['price']);?>;
	indiTestOrig[2] = <?php echo round($_products['hiv-lab']['price']);?>;
	indiTestOrig[3] = <?php echo round($_products['syphilis-lab']['price']);?>;
	indiTestOrig[4] = <?php echo round($_products['oralherpes-lab']['price']);?>;
	indiTestOrig[5] = <?php echo round($_products['genitalherpes-lab']['price']);?>;
	indiTestOrig[6] = <?php echo round($_products['hepatitis-b-lab']['price']);?>;
	indiTestOrig[7] = <?php echo round($_products['hepatitis-c-lab']['price']);?>;
	
var homeTestOrig = new Array();
	homeTestOrig[1] = <?php echo round($_products['at-home-STD-testing-for-men']['price']);?>;
	homeTestOrig[2] = <?php echo round($_products['at-home-STD-testing-for-women']['price']);?>;
	homeTestOrig[0] = <?php echo round($_products['hiv-home']['price']);?>;
	
var indiSkuArr = new Array();
	indiSkuArr[0] = 'chlamydia-lab';
	indiSkuArr[1] = 'gonorrhea-lab';
	indiSkuArr[2] = 'hiv-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'oralherpes-lab';
	indiSkuArr[5] = 'genitalherpes-lab';
	indiSkuArr[6] = 'hepatitis-b-lab';
	indiSkuArr[7] = 'hepatitis-c-lab';
	
var homeSkuArr = new Array();

	homeSkuArr[1] = 'at-home-STD-testing-for-men';
	homeSkuArr[2] = 'at-home-STD-testing-for-women';

	homeSkuArr[0] = 'hiv-home';
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		total = 0;
		
		price = 0;
		
		cartArr = new Array();
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = document.getElementById(el).value;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "<span style='color:#FFF;'>Total</span> $"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
			
			} else {
			
				document.getElementById('complete_package_hidden').value = 0;
			
			}
		
		}
		
	} else {
		
		re = 0;
	
		document.getElementById('complete_package_hidden').value = 0;
		
		document.getElementById('package').value = "";
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
		
			document.getElementById('indi_tests').checked = true;
			
			for (i = 0; i < homeSkuArr.length; i++) {
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
		
			document.getElementById('home_kit').checked = true;
			
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
				
		if (cartArr.length == 2 && el.indexOf('lab') > 0) {
		
			discount = 30;
					
		} 
		
		if (cartArr.length == 3 && el.indexOf('lab') > 0) {
		
			discount = 75;
					
		}
		
		if (cartArr.length == 4 && el.indexOf('lab') > 0) {
		
			discount = 165;
					
		}
		
		if (cartArr.length == 5 && el.indexOf('lab') > 0) {
		
			discount = 205;
					
		}
		
		if (cartArr.length == 6 && el.indexOf('lab') > 0) {
		
			discount = 295;
					
		}
		
		if (cartArr.length == 7 && el.indexOf('lab') > 0) {
		
			discount = 385;
					
		}
		
		if (cartArr.length == 8 && el.indexOf('lab') > 0) {
		
			discount = 475;
					
		} 
		
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 45;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 106;
    			
    			}
			}
		
		}
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 70;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 135;
    			
    			}
			}

		}
		
		if (cartArr.length == 4 && el.indexOf('home') > 0 ) {
		
			discount = 196;
		
		}
		
	
	   total = total + price;	
	
	   document.getElementById('widget_total').innerHTML = '<span style="color:#FFF;">Total</span> $'+(total-discount);
	
	}
	
}

</script>
<div class="bg_white">
<form name="productWidget" method="post" action="/customroute/index/checkout">
<div id="order_side_widget">
	<h3>Select your STD test(s)</h3>
	<h4><span class="input"><input type="radio" id="complete_package" value="<?php echo $_products['ultimate-8-pack-package-lab']['price'];?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>);" name="testType" /></span> <span class="text">8 Pack Comprehensive Package</span></h4>
	<div class="content">
		<input id="complete_package_hidden" type="hidden" value="<?php echo $_products['ultimate-8-pack-package-lab']['price'];?>" name="pack_<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>">
		<ul class="check">
			<li>Chlamydia</li>
			<li>Gonorrhea</li>
			<li>HIV</li>
			<li>Syphilis</li>
		</ul>
		<ul class="check">
			<li>Oral Herpes</li>
			<li>Genital Herpes</li>
			<li>Hepatitis B</li>
			<li>Hepatitis C</li>
		</ul>
		<div class="clear">&nbsp;</div>
	</div>
	<!-- /.content -->
	<h4><span class="input"><input type="radio" id="indi_tests" value="0" onClick="updateWidgetTotal(this.id,0);" name="testType" /></span> <span class="text">Individual STD Testing</span></h4>
	<div class="content">
		<ul>
			<li><input type="checkbox" value="<?php echo $_products['chlamydia-lab']['price'];?>" id="chlamydia-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['chlamydia-lab']['id'];?>);" name="indiTest[chlamydia-lab]" /> Chlamydia</li>
			<li><input type="checkbox" value="<?php echo $_products['gonorrhea-lab']['price'];?>" id="gonorrhea-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['gonorrhea-lab']['id'];?>);" name="indiTest[gonorrhea-lab]" /> Gonorrhea</li>
			<li><input type="checkbox" value="<?php echo $_products['oralherpes-lab']['price'];?>" id="oralherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['oralherpes-lab']['id'];?>);" name="indiTest[oralherpes-lab]" /> Oral Herpes</li>
			<li><input type="checkbox" value="<?php echo $_products['genitalherpes-lab']['price'];?>" id="genitalherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['genitalherpes-lab']['id'];?>);" name="indiTest[genitalherpes-lab]" /> Genital Herpes</li>
		</ul>
		<ul>
			<li><input type="checkbox" value="<?php echo $_products['syphilis-lab']['price'];?>" id="syphilis-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['syphilis-lab']['id'];?>);" name="indiTest[syphilis-lab]" /> Syphilis</li>
			<li><input type="checkbox" value="<?php echo $_products['hepatitis-b-lab']['price'];?>" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-b-lab']['id'];?>);" name="indiTest[hepatitis-b-lab]" /> Hepatitis B</li>
			<li><input type="checkbox" value="<?php echo $_products['hepatitis-c-lab']['price'];?>" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-c-lab']['id'];?>);" name="indiTest[hepatitis-c-lab]" /> Hepatitis C</li>
			<li><input type="checkbox" value="<?php echo $_products['hiv-lab']['price'];?>" id="hiv-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-lab']['id'];?>);" name="indiTest[hiv-lab]" /> HIV</li>
		</ul>
		<div class="clear">&nbsp;</div>
	</div>
	<!-- /.content -->
	<h4><span class="input"><input type="radio" value="0" id="home_kit" onClick="updateWidgetTotal(this.id,0);" name="testType" /> </span><span class="text">At-Home Tests</span></h4>
	<div class="content">
		<ul class="wide">
			<li><input type="checkbox" value="<?php echo $_products['at-home-STD-testing-for-women']['price'];?>" id="at-home-STD-testing-for-women" onClick="updateWidgetTotal(this.id,<?php echo $_products['at-home-STD-testing-for-women']['id'];?>);" name="homeTest[at-home-STD-testing-for-women]" /> <span class="blue">Women's Package</span><br />Chlamydia, Gonorrhea, Trichomoniasis</li>
			<li><input type="checkbox" value="<?php echo $_products['at-home-STD-testing-for-men']['price'];?>" id="at-home-STD-testing-for-men" onClick="updateWidgetTotal(this.id,<?php echo $_products['at-home-STD-testing-for-men']['id'];?>);" name="homeTest[at-home-STD-testing-for-men]" /> <span class="blue">Men's Package</span><br />Chlamydia, Gonorrhea, Trichomoniasis</li>
			<li><input type="checkbox" value="<?php echo $_products['hiv-home']['price'];?>" id="hiv-home" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-home']['id'];?>);" name="homeTest[hiv-home]" /><span class="blue">HIV</span></li>
		</ul>
		<div class="clear">&nbsp;</div>
	</div>
	<!-- /.content -->
	<div class="total">
		<div id="widget_total" style="font-size:17px;">Select Tests</div>
		<input type="submit" class="btn_orange" value="Order">
		<!-- <img src="/skin/frontend/default/stdtesting/images/arrow_right_white.png" alt="" /> order</a> -->
	</div>
</div>
<!-- /order_side_widget -->
        <input type="hidden" id="package" name="package" value="">
        </form>
        </div>