<?php

require_once('/home/webapps/sites/magento/public/rd/analytics_api.php');
require_once('/home/webapps/sites/magento/public/rd/datepicker.php');
require_once('/home/webapps/sites/magento/public/rd/maketable.php');
  
$login = 'getstdtested';
$password = 'Pinpoint4US';
$idg = 'ga:21076454';
 
$api = new analytics_api();
$api->login($login, $password);


$config  = Mage::getConfig()->getResourceConnectionConfig("default_setup");
	
	$db = new PDO ('mysql:dbname='.$config->dbname.';host='.$config->host, $config->username, $config->password);
	
	date_default_timezone_set('America/Chicago');
	
	if (!$_GET['start']) $_GET['start'] = date('m/d/Y');
	
	if (!$_GET['end']) $_GET['end'] = date('m/d/Y');
	
	$initStart = date('Y-m-d 00:00:00',strtotime($_GET['start']));
	
	$initEnd = date('Y-m-d 00:00:00',strtotime($_GET['end']));
	
	$start = gmdate('Y-m-d H:i:s',strtotime($initStart));	
	
	$startGa = gmdate('Y-m-d',strtotime($initStart));
	
	$end = gmdate('Y-m-d H:i:s',strtotime($initEnd));	
	
	$endGa = gmdate('Y-m-d',strtotime($initEnd));
	
?>
<style>

/* the div that holds the date picker calendar */
.dpDiv {
	}


/* the table (within the div) that holds the date picker calendar */
.dpTable {
	font-family: Tahoma, Arial, Helvetica, sans-serif;
	font-size: 12px;
	text-align: center;
	color: #505050;
	background-color: #ece9d8;
	border: 1px solid #AAAAAA;
	}


/* a table row that holds date numbers (either blank or 1-31) */
.dpTR {
	}


/* the top table row that holds the month, year, and forward/backward buttons */
.dpTitleTR {
	}


/* the second table row, that holds the names of days of the week (Mo, Tu, We, etc.) */
.dpDayTR {
	}


/* the bottom table row, that has the "This Month" and "Close" buttons */
.dpTodayButtonTR {
	}


/* a table cell that holds a date number (either blank or 1-31) */
.dpTD {
	border: 1px solid #ece9d8;
	}


/* a table cell that holds a highlighted day (usually either today's date or the current date field value) */
.dpDayHighlightTD {
	background-color: #CCCCCC;
	border: 1px solid #AAAAAA;
	}


/* the date number table cell that the mouse pointer is currently over (you can use contrasting colors to make it apparent which cell is being hovered over) */
.dpTDHover {
	background-color: #aca998;
	border: 1px solid #888888;
	cursor: pointer;
	color: red;
	}


/* the table cell that holds the name of the month and the year */
.dpTitleTD {
	}


/* a table cell that holds one of the forward/backward buttons */
.dpButtonTD {
	}


/* the table cell that holds the "This Month" or "Close" button at the bottom */
.dpTodayButtonTD {
	}


/* a table cell that holds the names of days of the week (Mo, Tu, We, etc.) */
.dpDayTD {
	background-color: #CCCCCC;
	border: 1px solid #AAAAAA;
	color: white;
	}


/* additional style information for the text that indicates the month and year */
.dpTitleText {
	font-size: 12px;
	color: gray;
	font-weight: bold;
	}


/* additional style information for the cell that holds a highlighted day (usually either today's date or the current date field value) */ 
.dpDayHighlight {
	color: 4060ff;
	font-weight: bold;
	}


/* the forward/backward buttons at the top */
.dpButton {
	font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif;
	font-size: 10px;
	color: gray;
	background: #d8e8ff;
	font-weight: bold;
	padding: 0px;
	}


/* the "This Month" and "Close" buttons at the bottom */
.dpTodayButton {
	font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif;
	font-size: 10px;
	color: gray;
	background: #d8e8ff;
	font-weight: bold;
	}
	
	
.repTable {

	border: 1px solid #000000;
	float: left;
	border-right: none;

}

.repCol {
	float: left;
	border-right: 1px solid #000000;
	width: 80px;
}

#tables {
    border-bottom: 0 none;
    padding-bottom: 0.5em;
    font-size: 11px;
    min-width: 1300px;
    width: 1300px;
}


#tables table {
	background-color: #FAFAFA;
    border: 1px solid #D6D6D6;
}

#tables tr.headings {
    background: url("http://admin.getstdtested.com/skin/adminhtml/default/enterprise/images/sort_row_bg.gif") repeat-x scroll 0 50% transparent;
}

#tables tr.headings th {
    border-color: #F9F9F9 #D1CFCF #F9F9F9 #F9F9F9;
    border-style: solid;
    border-width: 1px;
    font-size: 11px;
    

}



#tables th{

    color: #67767E;
    padding-bottom: 1px;
    padding-top: 2px;

}

#tables table td {
    border-color: #DADFE0;
    border-style: solid;
    border-width: 0 1px 1px 0;
}

#tables th, #tables td {
    padding: 2px 4px;
    font-size: 11px;
}

#tables .super{
    background: none repeat scroll 0 0 #6F8992;
    padding: 2px 10px;
    color: #FFFFFF;
    text-align: left;
}

</style>


<form action="" method="get">
	
	<input type="text" name="start" value="<?php echo ($startGa?date('m/d/Y',strtotime($startGa)):"");?>"><input type="button" value="select" onclick="displayDatePicker('start');">
	<input type="text" name="end" value="<?php echo ($endGa?date('m/d/Y',strtotime($endGa)):"");?>"><input type="button" value="select" onclick="displayDatePicker('end');">

	<select name="group">
		<option value="dates">Days</option>
		<option value="weeks">Week</option>
		<option value="months">Month</option>
	</select>
	
	<?php
	
	
	 $c = Mage::getModel('admin/user')->getCollection();
        
        $adminArr[99] = "ONLINE";

		foreach ($c->getItems() as $u) {
		
			$adminArr[$u->getUserId()] = $u->getUsername();
		
		}
	
	?>
	
	<select name="ppmd_rep">
		<option value=""></option>
		
		<?php
		
		foreach ($adminArr as $k=>$v) {
		
		?>
		
		<option <?php echo ($_GET['ppmd_rep'] == $k?"selected='selected'":""); ?> value="<?php echo $k; ?>"><?php echo $v;?></option>
		
		<?php } ?>
		
	</select>
	
	<?php $affilates = Mage::getModel('affiliates/affiliates')->getCollection();
   		$affilates->addFieldToFilter('callcenter',array('eq'=>1));
		$affilates->getSelect()->order(array('referral_id ASC'));
   					
		 ?>
	
	<select name="ppmd_affiliate">
		<option value=""></option>
		
		<?php
   		
   			foreach ($affilates as $affiliate) {
   					
   		?>		
   			
   			<option <?php echo ($_GET['ppmd_affiliate'] == $affiliate->getReferralId()?"selected='selected'":""); ?> value="<?php echo $affiliate->getReferralId();?>"><?php echo $affiliate->getReferralId();?></option>
   			
   		<?php	
   			}   		
   		?>
		
		
		
	</select>
	

	<button type="submit">Submit</button>

</form>

<br><br><br>

<?php
	
	$dates = getDays($startGa,$endGa);
	$weeks = getWeeks($startGa,$endGa);
	$months = getMonths($startGa,$endGa);
	
	$filter['dates'] = $dates;
	$filter['weeks'] = $weeks;
	$filter['months'] = $months;
	
	$arr = array();
	
echo "<div id='tables' style='min-width:1300px;'>";
	
	require_once('/home/webapps/sites/magento/public/rd/traffictable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/phonesalestable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/onlinesalestable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/totalsalestable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/phoneconversiontable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/onlineconversiontable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/averagetable.php');
	
	require_once('/home/webapps/sites/magento/public/rd/revenuetable.php');
	
	
	
echo "</div>";	
	
?><br><br>
<div style="clear:both;"></div>
<div style="clear:both; height:500px;">
<br><br>
<b>Total PN</b> =	Total phone and online PN orders<br>										
<b>Total PL</b> =	Total phone and online PL orders<br>											
<b>Total PC</b> =	Total phone and online PC orders<br>										
<b>Total Phone</b> =	Total number of phone orders regardless of type<br>									
<b>Total Online</b> =	Total number of online orders regardless of type<br>									
<b>Phone Conversion Rate PN</b> =	PN phone orders / # phone visitors<br>								
<b>Phone Conversion Rate Total</b> =	PN + PL + PC phone orders / # phone visitors <br>
<b>Online Conversion Rate PN</b> =	PN online orders / # online visitors<br>						
<b>Online Conversion Rate Total</b> = Online	PN + PL + PC online orders / # online visitors<br>
<b>Average Sales Price Phone</b>	= Average sales price of all test orders (PN/PC/PL)<br>									
<b>Average Sales Price Online</b> =	Average sales price of all test orders (PN/PC/PL)<br>
<b>Revenue Phone PN</b> =	Total revenue from PN phone orders<br>						
<b>Revenue Online PN</b> =	Total revenue from PN online orders<br>							
<b>Revenue Scripts</b> =	Total revenue from online and call center script orders<br>
<b>Revenue PL</b> =	Total cash collected by (day/week/month,etc) for PL orders<br>								
<b>Revenue PC</b> =	Total cash collected by (day/week/month,etc) for PC orders<br>							
<b>Refunds</b> =	Total refunds<br>
<b>SALES</b> =	Total sales including PN/PL/PC<br>						
<b>CASH</b> =	Total paid sales including PN/PL/PC MINUS refunds<br>								
</div>

