<script type="text/javascript"><!--
document.write(unescape("%3Cscript id='<?php echo $this->getPapAccountId() ?>' src='" + (("https:" == document.location.protocol) ? "https://" : "http://") +
        "partners.getlabtested.com/scripts/trackjs.js' type='text/javascript'%3E%3C/script%3E"));//-->
</script>
<script type="text/javascript"><!--
PostAffTracker.setAccountId('default1');
try {
    PostAffTracker.track();
} catch (err) { }
//-->
</script>