<?php

	//echo "<pre>";  print_r(Mage::getModel('core/session')->getData()); echo "</pre>";

	//$this = new Jag_Orderwidget_Block_Orderwidget;

	// echo get_class($this);

	$this->resetCart();



	$_products = $this->getProducts();

	$state = Mage::getSingleton('core/session')->getOrderState();

	$sZip = Mage::getSingleton('core/session')->getZip();

	if ($sZip) {
		$sesZip = $sZip;
	} else {
		$sesZip = 'Zip Code';
	}

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Local STD Testing</title>

	<link href='http://fonts.googleapis.com/css?family=Open+Sans:800italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/lp/05/css/styles.css" type="text/css" media="all" />
	<link rel="shortcut icon" href="/lp/05/images/favicon.ico" />

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />

	<meta name="robots" content="all" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	
	<script type="text/javascript" src="/js/prototype/prototype.js"></script>
	<script type="text/javascript" src="/js/lib/ccard.js"></script>
	<script type="text/javascript" src="/js/prototype/validation.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/builder.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/effects.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/dragdrop.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/controls.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/slider.js"></script>

	<script type="text/javascript" src="/js/varien/js.js"></script>
	<script type="text/javascript" src="/js/varien/form.js"></script>
	<script type="text/javascript" src="/js/varien/menu.js"></script>
	<script type="text/javascript" src="/js/mage/translate.js"></script>
	<script type="text/javascript" src="/js/mage/cookies.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/main.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/SpryAccordion.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/default/js/enterprise/catalogevent.js"></script>

	<script type="text/javascript" src="/skin/frontend/default/default/js/opcheckout.js"></script>
	
	<!-- Google Website Optimizer Tracking Script -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['gwo._setAccount', 'UA-10462432-2']);
	  _gaq.push(['gwo._trackPageview', '/1110561887/test']);
	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<!-- End of Google Website Optimizer Tracking Script -->
	
	<script type="text/javascript">
	//<![CDATA[
	Mage.Cookies.path     = '/';
	Mage.Cookies.domain   = '.getstdtested.com';
	//]]>
	</script>

	<script type="text/javascript">
	//<![CDATA[
	optionalZipCountries = [];
	//]]>
	</script>

</head>

<body>
	
	
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
	
	if (document.getElementById('zip_code').value.length != 5 ||is_int(document.getElementById('zip_code').value) === false) {			
	//if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder",array('_secure'=>false)) ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;

var ultimatePackage = 229;

var indiSkuArr = new Array();
	indiSkuArr[0] = 'hiv-lab';
	indiSkuArr[1] = 'chlamydia-gonorrhea-lab';
	indiSkuArr[2] = 'oral-genital-herpes-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'hepatitis-b-lab';
	indiSkuArr[5] = 'hepatitis-c-lab';
	indiSkuArr[6] = 'hiv-early-detection-lab';

var indiTestOrig = new Array();
	indiTestOrig[0] = 79;
	indiTestOrig[1] = 149;
	indiTestOrig[2] = 149;
	indiTestOrig[3] = 89;
	indiTestOrig[4] = 89;
	indiTestOrig[5] = 89;
	indiTestOrig[6] = 179;
	
	var homeSkuArr = new Array();
	homeSkuArr[0] = 'hiv-home';
	homeSkuArr[1] = 'chlamydia-gonorrhea-home';
	homeSkuArr[2] = 'trichomoniasis-home';
	
var homeTestOrig = new Array();
	homeTestOrig[0] = 99;
	homeTestOrig[1] = 149;
	homeTestOrig[2] = 199;
	
	
	
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		if (document.getElementById('hiv-early-detection-lab').checked == false) {
	
			total = 0;
			
			price = 0;
			
			cartArr = new Array();
		
		} else {
		
			total = 0;
		
			price = indiTestOrig[6];
				
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
		
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = parseInt(document.getElementById(el).value) + price;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 99;
    			
    			}
			}
	   	
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true && document.getElementById('hiv-early-detection-lab').checked == true) {
	
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('hiv-early-detection-lab').checked = false;
			
			document.getElementById('hiv-early-detection-lab').value = indiTestOrig[6];
			
			document.getElementById('package').value = "";
			
			total = 0;
		
		}
		
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
			
		}
		
		/*
if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').value < 0) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
		
		}
*/
		
	
		
		
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
			
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		
		if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').checked == false) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
			
			total = total + price;
		
		} else {
		
		total = total + price;
		
		}
		
			
	   	
	   	   
	
	   document.getElementById('widget_total').innerHTML = '$'+(total);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'expert_package') {
		
		//document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			//document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			//document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	
	//document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	/*
if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
*/
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>


<?php // PAP Header Tracking

if(isset($_GET['a_aid'])){ $_SESSION['a_aid'] = $_GET['a_aid']; } else { $_SESSION['a_aid'] = 0; }

if($_SESSION['a_aid']) { //create div for tracking
		
	$config  = Mage::getConfig()->getResourceConnectionConfig("default_setup");

	$db = new PDO ('mysql:dbname='.$config->dbname.';host='.$config->host, $config->username, $config->password);

	$affiliate_exists = false;
	
	Mage::getSingleton('core/session')->setAffiliateId($_SESSION['a_aid']);
	Mage::getSingleton('core/session')->setPpmdAffiliate($_SESSION['a_aid']);
	
	$q = 'select phone from affiliates where referral_id = "'.$_SESSION['a_aid'].'";';
	
		$sth = $db->prepare($q);
		$sth->setFetchMode(Zend_Db::FETCH_ASSOC);
    	$sth->execute();  
    		
    	$res = $sth->fetchAll();
    	
    	$sth = "";
    	        	    	
    $phone = $res[0]['phone'];

	if ($phone != ''){
				
			$phone = str_replace("-","",$phone);
			$phone = str_replace(".","",$phone);
			$phone = str_replace(" ","",$phone);
			
			$p1 = substr($phone,0,3);
			$p2 = substr($phone,3,3);
			$p3 = substr($phone,6,4);

			$phone = $p1."-".$p2."-".$p3;

		?>
		
		<div id="affiliate" style="display:none;">
			<div class="promoNumber">
				<?php echo $phone; ?>
			</div>
		</div>
		
		<?php
		
	} else {
	
		$phone = "866-749-6269";
	
	}	
	
}

// END PAP Header Tracking

?>

<div class="wrap">

	<div id="header">
		<div id="logo"><a href="#" title="Home | Get STD Tested">Get STD Tested</a></div>
		<div id="nav">
			<a href="#how">How it Works</a> &nbsp;|&nbsp;
			<a href="#getting-results">Getting Results</a> &nbsp;|&nbsp;
			<a href="#get-tested">Schedule Your Test</a> &nbsp;|&nbsp; or&nbsp;
			<span id="phone">Call 866-749-6269</span>
		</div>
	</div>

	<script type="text/javascript">	
		p = '<?php echo $phone; ?>';
		
		if (p.length > 6) {	
			document.getElementById('phone').innerHTML = 'Call <?php echo $phone; ?>';
		}	
	</script>	
	
	<div id="banner">
		<h1>Get Ahead of the Dating Game!</h1>
		<h2>Be prepared!</h2>
		<h3>Join 1000's of tested singles!</h3>
		<ul>
			<li>100% Confidential STD Testing</li>
			<li>Highest Quality and Accurate Testing</li>
			<li>Treatment Available in Most Cases</li>
		</ul>
		<div id="b-get-tested"><a href="#get-tested" title="Schedule Your Test Today">Get Tested Today</a></div>
	</div>
	
	<div class="canvas">

		<div id="trustbuilders">
			<p>Trusted by customers, the FDA and the sexual community</p>
			<p>Average Customer Review &ndash; <strong>4.5 out of 5 Stars</strong></p>
		</div>
		
		<div class="quote">
			<p>My doctor wouldn't have been able to see me for 2 months.<br /><span>I was able to get same day testing</span> through your service and<br />my test results came back sooner than 3 days.</p>
			<div>- Male, 36 from Illinois</div>
		</div>

		<a name="how"></a>
		<h2 id="h-how-it-works">How it Works?</h2>
		
		<ul id="how-it-works">
			<li id="how-it-works-1">
				<strong>1. Choose Your Tests</strong>
				<p>Select which STDs to test for and whether you'd prefer to be tested at home or at one of our 4,000 convenient lab locations. We accept credit / debit cards, e-checks and anoymous cash drop-off.</p>
			</li>
			<li id="how-it-works-2">
				<strong>2. Take The Test</strong>
				<p>Visit our nearest lab - we have over 4,000 locations - or take the test from the comfort of your own home and send the sample in.</p>
			</li>
			<li id="how-it-works-3">
				<strong>3. Check Your Results</strong>
				<p>Your test results will be ready within 3-5 days (faster than a doctor's office) and you'll be notified the second they are available. You can then view them via secure online portal or discuss them over the phone.</p>
			</li>
			<li id="how-it-works-4">
				<strong>4. Treatment Options</strong>
				<p>If the news isn't good, you still have options. Discuss your test with our in-house physicians to help interpret test results and answer questions. From medication to antibiotics, get private treatment.</p>
			</li>
		</ul>
		
		<h2 id="h-medical-board">Meet Our Medical Advisory Board &ndash; Accessible doctors focused on delivering accurate and private STD testing and treatment</h2>
		
		<div id="medical-board">

			<div class="medical-board-col">
				<img src="http://getstdtested.com/lp/05/images/medical-board-photo-1.jpg" width="240" height="175" border="0" alt="" />
				<h4>H. Hunter Handsfield, MD</h4>
				<p>With over 30+ years of experience and 250 publications under his belt, Dr. Handsfield has played an integral role in developing modern day STD prevention strategies.</p>
			</div>
			
			<div class="medical-board-col">
				<img src="http://getstdtested.com/lp/05/images/medical-board-photo-2.jpg" width="240" height="175" border="0" alt="" />
				<h4>Barbara Van Der Pol, PhD, MPH</h4>
				<p>Dr. Van Der Pol is a leading advisor for the Centers for Disease Control (CDC) and the National Chlamydia Coalition, performing cutting-edge STD research.</p>
			</div>
			
			<div class="medical-board-col">
				<img src="http://getstdtested.com/lp/05/images/medical-board-photo-3.jpg" width="240" height="175" border="0" alt="" />
				<h4>Neil S. Skolnik, MD</h4>
				<p>Dr. Skolnik is a well-known presenter and recent recipient of the "Top Doctor" Award in Family Medicine by Philadelphia Magazine, regularly contributing to CDC editorial.</p>
			</div>

		</div>
		
		<a href="#get-tested" title="Schedule Your Test Today" id="b-get-tested-today">Get Tested Today</a>

		<div class="phone-cta" id="phoneCTA">866-749-6269</div>

		<script type="text/javascript">	
			p = '<?php echo $phone; ?>';
			
			if (p.length > 6) {
				document.getElementById('phoneCTA').innerHTML = '<?php echo $phone; ?>';
			}	
		</script>
		
		<div class="quote">
			<p>I would recommend you and I will use your services again.<br /><span>I appreciate the convenience, confidentiality, and ease</span> with<br />which the tests are conducted.</p>
			<div>- Laura R. from Texas</div>
		</div>

		<a name="getting-results"></a>
		<h2 id="h-test-results">Getting Results</h2>

		<div class="col-left">
			<br /><img src="http://getstdtested.com/lp/05/images/sample-results.jpg" width="650" height="530" alt="" border="0" /><br /><br />
		</div>
		<div class="col-right">

			<div class="box_orange_header">
				<div class="header">
					<h3>View My Results</h3>
				</div>
				<div class="content">
					<form action="https://getstdtested.com/customer/account/loginPost" method="post">
						<span style="color: #1e6884; padding-bottom: 6px;">Email:<br /></span> <input class="text" name="login[username]" type="text" value="" /> 
						<span style="color: #1e6884; padding-bottom: 6px;">Password:<br /></span> <input class="text" name="login[password]" type="password" value="" />
						<div class="cboth"></div>
						<input class="submit" type="submit" value="login" />
						<div style="float: right; margin-top: 20px;"><a class="read_more" href="http://getstdtested.com/customer/account/forgotpassword/">forgot password?</a></div>
						<div class="cboth">&nbsp;</div>
					</form>
				</div>
			</div>
			
			<div class="cboth"><br /><br /></div>
			
			<a href="#get-tested" title="Order a Test Today" id="b-order-test-today">Order a Test Today</a>
		
		</div>
		<div class="cboth">&nbsp;</div>
		
		<div class="quote">
			<p>The process was completely thorough, quick,<br />fast, and everything was great. <span>It was everything I was<br />looking for</span> in this type of situation.</p>
			<div>- Mark W. from Ohio</div>
		</div>

		<a name="get-tested"></a>
		<h2 id="h-get-tested-today">Get Tested Today</h2>
		
		<div id="order">
		
			<h2 class="first">Tell us where you're located:</h2>

			<form onsubmit="return false;" id="location_form">
				<input type="text" onKeyPress="return submitenter(event);" class="text" id="zip_code" name="zip_code" value="Zip Code" maxlength="5" onfocus="javascript: if(this.value == 'Zip Code') this.value = '';" onblur="javascript: if(this.value == '') this.value = 'Zip Code';" />
				<input id="location_submit_button" class="b-submit" type="button" onClick="handlerFunction();return false;" value="Submit" />
				<img style="display:none; float:right; margin: 7px 200px 0 0;" id="ajax-loader-gif" src="http://getstdtested.com/media/images/ajax-loader.gif" />
			</form>
			<div class="cboth"><br /></div>
			
			<div id="location_results">
			
			<?php if ($state && Mage::helper('medivo')->isNNRState($state) && $labId =  Mage::getSingleton('core/session')->getLabId()) { ?>
				
				<?php 
					foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
						
						$labOpt = (array)$labOpt;
						
						if (isset($labOpt['id'])) $tlab = $labOpt['id'];
						if (isset($labOpt['nnr_id'])) $tlab = $labOpt['nnr_id'];
						
						if ($tlab == $labId && $labOpt['lab-id'] == 129) {	
			
					?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <?php echo $labOpt['address'];?><br>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</strong>
					</p>
					
					<?php 
					
						break;
					
					} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <br>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</strong>
					</p>
					
					<?php		
					
						}
						
					}
				
					?>
						
			<?php } else if ($state && !Mage::helper('medivo')->isNNRState($state) &&  $labId =  Mage::getSingleton('core/session')->getLabId()){
				
					foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
						
						if (isset($labOpt['id'])) $tlab = $labOpt['id'];
						if (isset($labOpt['nnr_id'])) $tlab = $labOpt['id'];
						
						if ($tlab == $labId && $labOpt['lab-id'] == 129) {	
			
			?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</strong>
					</p>
					
			
			<?php		} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</strong>
					</p>

					
			<?php		}
						
					}
			
			} else if ($state && !Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>
			
				<p>
					<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
					<strong>We have 6+ testing locations near you. Select your preferred location during checkout.</strong>
				</p>
			
			<?php }  else if ($state && Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>

				<p>
					<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
					<strong>We have 6+ testing locations near you. However, pricing varies due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>. Proceed to checkout to identify your preferred location and view local pricing.</strong>
				</p>

			<?php } else { ?>
				
				<p><strong>For test availability and local pricing, please enter your zip code.</strong></p>
				
			<?php } ?>
			
			</div>
			<div class="cboth"></div>

                    <div id="order_module2">
					
                    	<form name="orderWidget" id="orderWidget" method="post" action="http://getstdtested.com/customroute/index/checkout">

                            <div id="at_home">
                                <div class="header">At-Home Testing</div>
                                <div class="content">
                                    <ul>
                                        <li><input type="checkbox" value="105.0000" id="hiv-home" onClick="updateWidgetTotal(this.id,4);toggleCartElement(this.id);" name="homeTest[hiv-home]" /><label for="hiv-home">HIV Standard</label></li>
										<li class="price">$105</li>
                                    	<li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<?php } ?> type="checkbox" value="165.0000" id="chlamydia-gonorrhea-home" onClick="updateWidgetTotal(this.id,44);toggleCartElement(this.id);" name="homeTest[chlamydia-gonorrhea-home]" /><label for="chlamydia-gonorrhea-home">Chlamydia &amp; Gonorrhea</label></li>
										<li class="price">$165</li>
                                        <li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<?php } ?> type="checkbox" value="205.0000" id="trichomoniasis-home" onClick="updateWidgetTotal(this.id,3);toggleCartElement(this.id);" name="homeTest[trichomoniasis-home]" /><label for="trichomoniasis-home">Trichomoniasis</label></li>
										<li class="price">$205</li>
                                    </ul>
                                </div>
                            </div>

                            <div id="lab_package">
                                <div class="header">Complete Lab Testing Package</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li>HIV Standard</li>
                                        <li>Chlamydia</li>
                                        <li>Gonorrhea</li>
                                        <li>Oral Herpes</li>
                                        <li>Genital Herpes</li>
                                        <li>Syphilis</li>
                                        <li>Hepatitis B</li>
                                        <li>Hepatitis C</li>
                                    </ul>
									<div style="clear: both;"></div>
                                </div>
								<div id="lab_packapge_footer">
									<span class="price">$229</span>
									<input type="radio" id="expert_package" value="229" onClick="updateWidgetTotal(this.id,14);toggleCartElement(this.id);" name="testPackage" />
									<label for="expert_package">ADD TO CART</label>
									<input id="expert_package_hidden" type="hidden" name="pack_14" value="229">
									<div style="clear: both;"></div>
								</div>
                            </div>

                            <div id="lab_tests1">
                                <div class="header">Lab Testing</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li><input type="checkbox" value="79.0000" id="hiv-lab" onClick="updateWidgetTotal(this.id,11);toggleCartElement(this.id);" name="indiTest[hiv-lab]" /><label for="hiv-lab">HIV Standard</label></li>
										<li class="price">$79</li>
                                        <li><input type="checkbox" value="149.0000" id="chlamydia-gonorrhea-lab" onClick="updateWidgetTotal(this.id,40);toggleCartElement(this.id);" name="indiTest[chlamydia-gonorrhea-lab]" /><label for="chlamydia-gonorrhea-lab">Chlamydia &amp; Gonorrhea</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="149.0000" id="oral-genital-herpes-lab" onClick="updateWidgetTotal(this.id,42);toggleCartElement(this.id);" name="indiTest[oral-genital-herpes-lab]" /><label for="oral-genital-herpes-lab">Oral &amp; Genital Herpes</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="89.0000" id="syphilis-lab" onClick="updateWidgetTotal(this.id,12);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" /><label for="syphilis-lab">Syphilis</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,7);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" /><label for="hepatitis-b-lab">Hepatitis B</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,8);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" /><label for="hepatitis-c-lab">Hepatitis C</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" <?php if (Mage::getSingleton('core/session')->getLabType() == 119) { ?> disabled="disabled" <?php } ?> value="179.0000" id="hiv-early-detection-lab" onClick="updateWidgetTotal(this.id,13);toggleCartElement(this.id);" name="indiTest[hiv-early-detection-lab]" /><label for="hiv-early-detection-lab">HIV Early Detection *</label></li>
										<li class="price">$179</li>
                                    </ul>
                                </div>
                            </div>

							<div id="your_order">                                    
                                <div class="total">
                                	ORDER TOTAL<br />
                                    <span id="total_price"><div id="widget_total">$0</div></span>
                                </div>
                                <input type="button" onclick="checkEmpty();" class="submit btn_orange_32_reflection" value="continue" style="width: 125px;" />
                            </div>
							
							<input type="hidden" id="package" name="package" value="">  							
							
						</form>
						<div id="expert_package-cart" style="display:none;"></div>
					</div>
		
			<div id="trustbuilders2">
				<p>Trusted by customers, the FDA and the sexual community</p>
				<p>Average Customer Review &ndash; <strong>4.5 out of 5 Stars</strong></p>
			</div>
				
		</div>
		<div class="cboth"><br /></div>
	
	</div>
	
	<div id="footer">
		<div class="col-left">
			<h2>About Ourselves</h2>
			<p><span>GetSTDtested.com is America's leading and most trusted online STD testing clinic&nbsp;&ndash;&nbsp;providing you peace of mind through confidential, accurate, and convenient&nbsp;STD testing and STD information.</span></p>
		</div>
		<div class="col-right">
			<h2 style="font-size: 26px;">Schedule Test Today</h2>
			<p><a href="#get-tested" id="b-see-testing-options">See Testing Options</a></p>
		</div>
		<div class="col-left">
			<p>&copy; 2012 getSTDtested.com. All rights reserved. &nbsp;|&nbsp; <a href="http://getstdtested.com/terms-of-service">Terms &amp; Conditions</a> &nbsp;|&nbsp; <a href="http://getstdtested.com/privacy-policy">Privacy Policy</a></p>
		</div>
		<div class="col-right">
			<p><span id="footerPhone">Call 866-749-6269</span></p>

			<script type="text/javascript">	
				p = '<?php echo $phone; ?>';
				
				if (p.length > 6) {
					document.getElementById('footerPhone').innerHTML = 'Call <?php echo $phone; ?>';
				}	
			</script>
			
		</div>
		<div class="cboth">&nbsp;</div>
	</div>
		
	<!-- Google Analytics Tracking -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-10462432-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>		
	<!-- EOF Google Analytics Tracking -->

	<!-- Google Code for GST Visitors 1 Remarketing List -->
	<script type="text/javascript">
	/* <![CDATA[ */
	var google_conversion_id = 1047469408;
	var google_conversion_language = "en";
	var google_conversion_format = "3";
	var google_conversion_color = "666666";
	var google_conversion_label = "w3GLCNrD9AEQ4Lq88wM";
	var google_conversion_value = 0;
	/* ]]> */
	</script>
	<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
	</script>
	<noscript>
	<div style="display:inline;">
	<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1047469408/?label=w3GLCNrD9AEQ4Lq88wM&amp;guid=ON&amp;script=0"/>
	</div>
	</noscript>
	<!-- End of Google Code for GST Visitors 1 Remarketing List -->

	<!-- Start of Zopim Live Chat Script -->
	<script type="text/javascript">
	window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=
	z.s=d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o
	){z.set._.push(o)};$.setAttribute('charset','utf-8');$.async=!0;z.set.
	_=[];$.src=('https:'==d.location.protocol?'https://ssl':'http://cdn')+
	'.zopim.com/?uBwYwCVwg065nQ32d19kYDqQ6a1l91wt';$.type='text/java'+s;z.
	t=+new Date;z._=[];e.parentNode.insertBefore($,e)})(document,'script')
	</script>
	<!-- End of Zopim Live Chat Script -->

	<!-- Begin adBrite, important page views tracking -->
	<img src="http://bstats.adbrite.com/adserver/behavioral-data/0?d=47384704;bapid=10251;uid=845986" border="0" hspace="0" vspace="0" width="1" height="1"/> 
	<!-- End adBrite, important page views tracking -->

	<!-- AdRoll Remarketing Code -->
	<script type="text/javascript">
	adroll_adv_id = "OBD5PEJZNRCB3PQUJMOZ65";
	adroll_pix_id = "V6VV7AXHKZHE3JSOL2EKB5";
	(function () {
	var oldonload = window.onload;
	window.onload = function(){
	   __adroll_loaded=true;
	   var scr = document.createElement("script");
	   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
	   scr.setAttribute('async', 'true');
	   scr.type = "text/javascript";
	   scr.src = host + "/j/roundtrip.js";
	   ((document.getElementsByTagName('head') || [null])[0] ||
		document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
	   if(oldonload){oldonload()}};
	}());
	</script>
	<!-- EOF AdRoll Remarketing Code -->

</div>


</body>
</html>

