<?php

$this->resetCart();

//$_products = $this->getProducts();

$state = Mage::getSingleton('core/session')->getOrderState();

$sZip = substr(Mage::getSingleton('core/session')->getZip(),0,5);

if ($sZip) {

	$sesZip = $sZip;

} else {

	$sesZip = 'Enter Zip Code';

}

//echo "<pre>"; print_r(Mage::getSingleton('core/session')->getData()); echo "</pre>"; 

?>
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
				
	if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder") ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;

var ultimatePackage = 229;

var indiSkuArr = new Array();
	indiSkuArr[0] = 'hiv-lab';
	indiSkuArr[1] = 'chlamydia-gonorrhea-lab';
	indiSkuArr[2] = 'oral-genital-herpes-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'hepatitis-b-lab';
	indiSkuArr[5] = 'hepatitis-c-lab';
	indiSkuArr[6] = 'hiv-early-detection-lab';

var indiTestOrig = new Array();
	indiTestOrig[0] = 79;
	indiTestOrig[1] = 149;
	indiTestOrig[2] = 149;
	indiTestOrig[3] = 89;
	indiTestOrig[4] = 89;
	indiTestOrig[5] = 89;
	indiTestOrig[6] = 179;
	
	var homeSkuArr = new Array();
	homeSkuArr[0] = 'hiv-home';
	homeSkuArr[1] = 'chlamydia-gonorrhea-home';
	homeSkuArr[2] = 'trichomoniasis-home';
	
var homeTestOrig = new Array();
	homeTestOrig[0] = 105;
	homeTestOrig[1] = 165;
	homeTestOrig[2] = 205;
	
	
	
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		if (document.getElementById('hiv-early-detection-lab').checked == false) {
	
			total = 0;
			
			price = 0;
			
			cartArr = new Array();
		
		} else {
		
			total = 0;
		
			price = indiTestOrig[6];
				
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
		
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = parseInt(document.getElementById(el).value) + price;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true && document.getElementById('hiv-early-detection-lab').checked == true) {
	
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('hiv-early-detection-lab').checked = false;
			
			document.getElementById('hiv-early-detection-lab').value = indiTestOrig[6];
			
			document.getElementById('package').value = "";
			
			total = 0;
		
		}
		
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
			
		}
		
		/*
if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').value < 0) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
		
		}
*/
		
	
		
		
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
			
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		
		if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').checked == false) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
			
			total = total + price;
		
		} else {
		
		total = total + price;
		
		}
		
			
	   	
	   	   
	
	   document.getElementById('widget_total').innerHTML = '$'+(total);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'expert_package') {
		
		document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			//document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			//document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	
	//document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	/*
if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
*/
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>
<div class="clear"></div>
            <div class="sep10"></div>

            <div id="content">
            	
                <div id="order">

<link href='http://fonts.googleapis.com/css?family=Open+Sans:700' rel='stylesheet' type='text/css'>
<link media="all" href="/skin/frontend/default/getstdtested/css/orderwidget-lab-only.css" type="text/css" rel="stylesheet">

					<h1>Customize your STD Test or choose the popular <em>Complete Package</em></h1>

                    <div id="order_module2">
					
                    	<form name="orderWidget" id="orderWidget" method="post" action="http://getstdtested.com/customroute/index/checkout">

                            <input type="checkbox" value="105.0000" id="hiv-home" name="homeTest[hiv-home]" style="display: none;" />
                            <input type="checkbox" value="165.0000" id="chlamydia-gonorrhea-home" name="homeTest[chlamydia-gonorrhea-home]" style="display: none;" />
                            <input type="checkbox" value="205.0000" id="trichomoniasis-home" name="homeTest[trichomoniasis-home]" style="display: none;" />

                            <div id="lab_package">
                                <div class="header">Complete Lab Testing Package</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li>HIV Standard</li>
                                        <li>Chlamydia</li>
                                        <li>Gonorrhea</li>
                                        <li>Oral Herpes</li>
                                        <li>Genital Herpes</li>
                                        <li>Syphilis</li>
                                        <li>Hepatitis B</li>
                                        <li>Hepatitis C</li>
                                    </ul>
									<div style="clear: both;"></div>
                                </div>
								<div id="lab_packapge_footer">
									<span class="price">$229</span>
									<input type="radio" id="expert_package" value="229" onClick="updateWidgetTotal(this.id,14);toggleCartElement(this.id);" name="testPackage" />
									<label for="expert_package">ADD TO CART</label>
									<input id="expert_package_hidden" type="hidden" name="pack_14" value="229">
									<div style="clear: both;"></div>
								</div>
                            </div>

                            <div id="lab_tests1">
                                <div class="header">Lab Testing</div>
                                <div class="content">
                                    <ul>                                    	
                                        <li><input type="checkbox" value="79.0000" id="hiv-lab" onClick="updateWidgetTotal(this.id,11);toggleCartElement(this.id);" name="indiTest[hiv-lab]" /><label for="hiv-lab">HIV Standard</label></li>
										<li class="price">$79</li>
                                        <li><input type="checkbox" value="149.0000" id="chlamydia-gonorrhea-lab" onClick="updateWidgetTotal(this.id,40);toggleCartElement(this.id);" name="indiTest[chlamydia-gonorrhea-lab]" /><label for="chlamydia-gonorrhea-lab">Chlamydia &amp; Gonorrhea</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="149.0000" id="oral-genital-herpes-lab" onClick="updateWidgetTotal(this.id,42);toggleCartElement(this.id);" name="indiTest[oral-genital-herpes-lab]" /><label for="oral-genital-herpes-lab">Oral &amp; Genital Herpes</label></li>
										<li class="price">$149</li>
                                        <li><input type="checkbox" value="89.0000" id="syphilis-lab" onClick="updateWidgetTotal(this.id,12);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" /><label for="syphilis-lab">Syphilis</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,7);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" /><label for="hepatitis-b-lab">Hepatitis B</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="89.0000" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,8);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" /><label for="hepatitis-c-lab">Hepatitis C</label></li>
										<li class="price">$89</li>
                                        <li><input type="checkbox" value="179.0000" id="hiv-early-detection-lab" onClick="updateWidgetTotal(this.id,13);toggleCartElement(this.id);" name="indiTest[hiv-early-detection-lab]" /><label for="hiv-early-detection-lab">HIV Early Detection *</label></li>
										<li class="price">$179</li>
                                    </ul>
                                </div>
                            </div>

							<div id="your_order">                                    
                                <div class="total">
                                	ORDER TOTAL<br />
                                    <span id="total_price"><div id="widget_total">$0</div></span>
                                </div>
                                <input type="button" onclick="checkEmpty();" class="submit btn_orange_32_reflection" value="continue" style="width: 125px;" />
                            </div>
							
							<input type="hidden" id="package" name="package" value="">  							
							
						</form>
						<div id="expert_package-cart" style="display:none;"></div>
					</div>
                    
                    <div class="clear">&nbsp;</div>
                    <div class="sep20">&nbsp;</div>
					
					<div id="trustbuilders">

						<div class="col">					
							<div class="box">
								<p>
									<img src="/skin/frontend/default/getstdtested/images/trusted_logos_nbc.jpg" width="235" height="100" alt="" /><br />
									"...one Chicago-area company said it's got a business that could help. Their tests screen for two of the most common STD's &mdash; chlamydia and gonorrhea."
									<small>-Nesita Kwan, NBC Chicago</small>
								</p>
							</div>
						</div>
					
						<div class="col">					
							<div class="box">
								<p>
									<img src="/skin/frontend/default/getstdtested/images/trusted_logos_wsj.jpg" width="235" height="100" alt="" /><br />
									"A for-profit start-up company called GetSTDTested.com last month launched a Web site with the same name that refers people 18 years old and over to local labs for chlamydia and other STD tests. The site allows users to obtain a doctor's order, pay for the tests and get confidential results online."
									<small>-Melinda Beck, Wall Street Journal</small>
								</p>
							</div>
						</div>
					
						<div class="col-last">					
							<div class="box">
								<p>
									<img src="/skin/frontend/default/getstdtested/images/trusted_logos_asha.jpg" width="235" height="100" alt="" /><br />
									"The tricky thing is this can all happen even in someone with an STD who has few &ndash;if any&ndash; symptoms. Anyone who tests positive for any sexually transmitted infection should consider testing for others."
									<small>-Fred Wyand, Director at the<br />American Social Health Association</small>
								</p>
							</div>
						</div>
					
					</div>
                    
					<div class="cboth"><br /><br /></div>
                    <p class="acenter"><img src="/skin/frontend/default/getstdtested/images/reviews_stars_v2.jpg" width="595" height="68" alt="" /></p>
					
					<div id="faqs">
					
						<h2>Still have questions about your STD test?</h2>
					
						<div class="col3">
							<h3>How are the tests administered?</h3>
							<p>Chlamydia and gonorrhea tests require a urine sample, while hepatitis, herpes, HIV and syphilis tests use a blood sample. Testing is quick and non-invasive; there is no painful swabbing or need to undress&ndash;ever.</p>
						</div>
					
						<div class="col3">
							<h3>I don't want anyone to know I'm testing for STDs. How will my privacy be protected?</h3>
							<p>All labs offer more than STD testing, so no one in the waiting room will know why you are there; results are housed in a secure, password-protected portal; and billing is discreet. Also, there are no ties to insurance or medical records.</p>
						</div>
					
						<div class="col3-last">
							<h3>I just placed my order. How soon can I test?</h3>
							<p>Today. Once you place your order, you will receive an email with testing instructions and your requisition form. Simply print the forms and test any time during the lab's operating hours. If you don't have a printer, contact us and we will be happy to fax it to the lab for you.</p>
						</div>
						
						<div class="cboth"><br /></div>
					
						<div class="col3">
							<h3>Do you accept health insurance?</h3>
							<p>Due to the private nature of our business, we do not accept health insurance. However, by request, we can issue an itemized receipt that you can submit to your insurance company.</p>
						</div>
					
						<div class="col3">
							<h3>How accurate are these tests?</h3>
							<p>We use the same STD tests that you would receive at a hospital &mdash; so be assured you are testing with the most accurate tests available.</p>
						</div>
					
						<div class="col3-last">
							<h3>Is there any special preparation needed before testing?</h3>
							<p>If you are testing for gonorrhea and/or chlamydia, avoid urinating an hour before testing. Besides that, there's no preparation required.</p>
						</div>
						
						<div class="cboth"><br /></div>
					
						<div class="col3">
							<h3>How do I access my results?</h3>
							<p>On average, results return within 3 business days after visiting the lab&ndash;faster than a doctor's office. Results can take up to 5 days.</p>
						</div>
					
						<div class="col3">
							<h3>When will my results be ready?</h3>
							<p>Results are accessible through our secure, online portal. For ultimate privacy, results are protected with your personal password. We can also discuss your results over the phone.</p>
						</div>
					
						<div class="col3-last">
							<h3>Do you offer treatment for STDs if I'm positive?</h3>
							<p>Our staff physicians can prescribe antibiotics to cure the most common STDs, including chlamydia and gonorrhea. Medication for herpes is also available.</p>
						</div>
					
					</div>
					
					<div id="why-us">
					
						<div id="col1">
							<div class="box">
								<h3>Satisfied Patients</h3>
								<p class="textItem">
									"I will definitely use you again, this process was completely thorough, quick, fast, &amp; everything was great. All of you are very friendly, it was everything I was looking for in this type of situation."
									<small>-Mark W. from Ohio</small>
								</p>
								<p class="textItem">
									"I was treated very nicely, everything was very quick, I will recommend you to anyone who needs to be tested, your service was well worth the $90, for what I received. Thank you very much!"
									<small>-Richard Y, North Carolina</small>
								</p>
								<p class="textItem">
									"Yes I would us this service again. Hopefully it will never happen again, but if anything arises, I will use you guys!"
									<small>-Toby P, Washington</small>
								</p>
								<p class="textItem">
									"Yes I would definitely use you and in the future and recommend you guys. I&nbsp;appreciated the confidentially and cash options."
									<small>-Walter W, Texas</small>
								</p>
								<div class="cboth"></div>
							</div>
						</div>
					
						<div id="col2">
							<div class="box">
								<h3>Why Choose Us?</h3>
								<ul>
									<li>The most accurate tests on the market</li>
									<li>Fastest results in 3 to 5 days</li>
									<li>100% confidential &ndash; No affiliation with your medical or billing records</li>
									<li>Easy online scheduling &amp; private results portal</li>
									<li>Satisfaction guaranteed</li>
								</ul>
							</div>
						</div>
					
						<div id="col3">
							<div class="box">
								<h3>Sample Test Results</h3>
								<p class="acenter"><a class="preview" href="javascript:void(0);" rel="http://getstdtested.com/media/images/your_results-small.png"><img src="http://getstdtested.com/media/images/your_results-small.png" border="0" alt="Get Results" width="250" height="198" /></a></p>
							</div>
						</div>					
					
					</div>
                    
                    <div class="clear">&nbsp;</div>
                    <div class="sep20">&nbsp;</div>
                    <div class="sep20">&nbsp;</div>
					
					<p class="acenter"><a href="#order" title="Select Your Test"><img src="http://getstdtested.com/skin/frontend/default/getstdtested/images/b-select-your-test.jpg" border="0" alt="Select Your Test" width="335" height="93" /></a></p>

                    <div class="sep20">&nbsp;</div>

                </div> <!-- /order -->
                
            </div> <!-- /content -->
			
<script type="text/javascript">

this.imagePreview = function(){	

	/* CONFIG */
	xOffset = 10;
	yOffset = 10;

	jQuery("a.preview").hover(function(e){
		this.t = this.title;
		this.title = "";	
		var c = (this.t != "") ? "<br />" + this.t : "";
		jQuery("body").append("<p id='preview'><img src='"+ this.rel +"' alt='Image preview' />"+ c +"</p>");								 
		jQuery("#preview")
		.css("top",(e.pageY - xOffset) + "px")
		.css("left",(e.pageX + yOffset) + "px")
		.fadeIn("fast");						
	},
	function(){
		this.title = this.t;	
		jQuery("#preview").remove();
		});	
		jQuery("a.preview").mousemove(function(e){
		jQuery("#preview")
		.css("top",(e.pageY - xOffset) + "px")
		.css("left",(e.pageX + yOffset) + "px");
	});			
};

jQuery.fn.quovolver = function(speed, delay) {
	
	/* Sets default values */
	if (!speed) speed = 500;
	if (!delay) delay = 6000;
	
	// If "delay" is less than 4 times the "speed", it will break the effect 
	// If that's the case, make "delay" exactly 4 times "speed"
	var quaSpd = (speed*4);
	if (quaSpd > (delay)) delay = quaSpd;
	
	// Create the variables needed
	var	quote = $(this),
		firstQuo = jQuery(this).filter(':first'),
		lastQuo = jQuery(this).filter(':last'),
		wrapElem = '<div id="quote_wrap"></div>';
	
	// Wrap the quotes
	jQuery(this).wrapAll(wrapElem);
	
	// Hide all the quotes, then show the first
	jQuery(this).hide();
	jQuery(firstQuo).show();
	
	// Set the hight of the wrapper
	jQuery(this).parent().css({height: jQuery(firstQuo).height()});		
	
	// Where the magic happens
	setInterval(function(){
		
		// Set required hight and element in variables for animation
		if(jQuery(lastQuo).is(':visible')) {
			var nextElem = jQuery(firstQuo);
			var wrapHeight = jQuery(nextElem).height();
		} else {
			var nextElem = jQuery(quote).filter(':visible').next();
			var wrapHeight = jQuery(nextElem).height();
		}
		
		// Fadeout the quote that is currently visible
		jQuery(quote).filter(':visible').fadeOut(speed);
		
		// Set the wrapper to the hight of the next element, then fade that element in
		setTimeout(function() {
			jQuery(quote).parent().animate({height: wrapHeight}, speed);
		}, speed);
		
		if(jQuery(lastQuo).is(':visible')) {
			setTimeout(function() {
				jQuery(firstQuo).fadeIn(speed*2);
			}, speed*2);
			
		} else {
			setTimeout(function() {
				jQuery(nextElem).fadeIn(speed);
			}, speed*2);
		}
		
	}, delay);

};

jQuery(document).ready(function(){
	imagePreview();
	jQuery('.textItem').quovolver();
});

</script>
