<?php

//echo "<pre>";  print_r(Mage::getModel('core/session')->getData()); echo "</pre>";

$this->resetCart();



$_products = $this->getProducts();

$state = Mage::getSingleton('core/session')->getOrderState();

$sZip = Mage::getSingleton('core/session')->getZip();

if ($sZip) {

	$sesZip = $sZip;

} else {

	$sesZip = 'Zip Code';

}


?>
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
				
	if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder") ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;
var ultimatePackage = 249;

var indiTestOrig = new Array();
	indiTestOrig[0] = <?php echo round($_products['chlamydia-lab']['price']);?>;
	indiTestOrig[1] = <?php echo round($_products['gonorrhea-lab']['price']);?>;
	indiTestOrig[2] = <?php echo round($_products['hiv-lab']['price']);?>;
	indiTestOrig[3] = <?php echo round($_products['syphilis-lab']['price']);?>;
	indiTestOrig[4] = <?php echo round($_products['oralherpes-lab']['price']);?>;
	indiTestOrig[5] = <?php echo round($_products['genitalherpes-lab']['price']);?>;
	indiTestOrig[6] = <?php echo round($_products['hepatitis-b-lab']['price']);?>;
	indiTestOrig[7] = <?php echo round($_products['hepatitis-c-lab']['price']);?>;
	
var homeTestOrig = new Array();
	homeTestOrig[1] = <?php echo round($_products['at-home-STD-testing-for-men']['price']);?>;
	homeTestOrig[2] = <?php echo round($_products['at-home-STD-testing-for-women']['price']);?>;
	homeTestOrig[0] = <?php echo round($_products['hiv-home']['price']);?>;
	
var indiSkuArr = new Array();
	indiSkuArr[0] = 'chlamydia-lab';
	indiSkuArr[1] = 'gonorrhea-lab';
	indiSkuArr[2] = 'hiv-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'oralherpes-lab';
	indiSkuArr[5] = 'genitalherpes-lab';
	indiSkuArr[6] = 'hepatitis-b-lab';
	indiSkuArr[7] = 'hepatitis-c-lab';
	
var homeSkuArr = new Array();

	homeSkuArr[1] = 'at-home-STD-testing-for-men';
	homeSkuArr[2] = 'at-home-STD-testing-for-women';

	homeSkuArr[0] = 'hiv-home';
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		total = 0;
		
		price = 0;
		
		cartArr = new Array();
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = document.getElementById(el).value;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
			
			} else {
			
				document.getElementById('complete_package_hidden').value = 0;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	// if (cartArr.length == 0) {
// 	   		
	   		// total = 0;
// 	   		
	   	// }
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		document.getElementById('complete_package_hidden').value = 0;
		
		document.getElementById('complete_package').checked = false;
		
		document.getElementById('package').value = "";
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
				
		if (cartArr.length == 2 && el.indexOf('lab') > 0) {
		
			discount = 30;
					
		} 
		
		if (cartArr.length == 3 && el.indexOf('lab') > 0) {
		
			discount = 75;
					
		}
		
		if (cartArr.length == 4 && el.indexOf('lab') > 0) {
		
			discount = 165;
					
		}
		
		if (cartArr.length == 5 && el.indexOf('lab') > 0) {
		
			discount = 205;
					
		}
		
		if (cartArr.length == 6 && el.indexOf('lab') > 0) {
		
			discount = 295;
					
		}
		
		if (cartArr.length == 7 && el.indexOf('lab') > 0) {
		
			discount = 385;
					
		}
		
		if (cartArr.length == 8 && el.indexOf('lab') > 0) {
		
			discount = 475;
					
		}
		
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 45;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] != 'trichomoniasis-home'){
    			
    				discount = 106;
    			
    			}
			}
		
		}
		
		if (cartArr.length == 2 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 70;
    			
    			}
			}

		}
		
		if (cartArr.length == 3 && el.indexOf('home') > 0 ) {
		
			for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'trichomoniasis-home'){
    			
    				discount = 135;
    			
    			}
			}

		}
		
		if (cartArr.length == 4 && el.indexOf('home') > 0 ) {
		
			discount = 196;
		
		}
		
	
	   total = total + price;	
	   
	   <?php } else  { ?>
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	if (cartArr.length == 0) {
	   		
	   		total = 0;
	   		
	   	}
	   	
	   <?php } ?>
	
	   document.getElementById('widget_total').innerHTML = 'Total: '+'$'+(total-discount);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked && !document.getElementById('expert_package').checked && !document.getElementById('complete_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'complete_package') {
		
		document.getElementById('expert_package-cart').style.display = 'none';
		document.getElementById('complete_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
		
		
	
	} else if (el == 'expert_package') {
		
		document.getElementById('complete_package-cart').style.display = 'none';
		document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
		
	document.getElementById('complete_package-cart').style.display = 'none';
	
	document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>

<div class="clear"></div>
<div class="sep10"></div>
            	
<div id="order_wide_content" class="box_grey_border">

	<div id="questions_white_short_widget">
        <h4>Questions?</h4>
        <p class="blue">Or to order by phone</p>
        <p class="large">
            <span class="blue">Call us at:</span> <span class="orange">866-749-6269</span>
        </p>
        <p>
            M-F 7am-7pm Sat-Sun 9am-3pm CST
        </p>
    </div>
            
	
		<?php 
		
       	if ($labId =  Mage::getSingleton('core/session')->getLabId()){

		?>

		<h2 class="first">1. Your Testing Location: </h2>

		<?php		

		} else { 
		
		?>
		
		<h2 class="first">1. Tell us where you're located: </h2>
		
		<?php
		
		}
		
		?>
	
	<?php if (!$labId =  Mage::getSingleton('core/session')->getLabId()){ ?>
	<form onsubmit="return false;" id="location_form">
    	<input type="text" onKeyPress="return submitenter(event);"  class="text" id="zip_code" name="zip_code" value="<?php echo ($zip = $this->getRequest()->getPost('zip_code')? $zip : $sesZip);?>" onfocus="javascript: if(this.value == 'Zip Code') this.value = '';" onblur="javascript: if(this.value == '') this.value = 'Zip Code';" />
        <input id="location_submit_button" class="submit btn_orange_32_reflection" type="button" onClick="handlerFunction();return false;" value="Submit" />
    	<img style="display:none;float:right;margin-right: 47%;" id="ajax-loader-gif" src="/media/images/ajax-loader.gif" />
    </form>
    

    <?php } ?>
	
	<div id="location_results">
		
		<?php if ($state && Mage::helper('medivo')->isNNRState($state) && $labId =  Mage::getSingleton('core/session')->getLabId()) { ?>
	
		<?php 
		foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
			
			$labOpt = (array)$labOpt;
			
			if (isset($labOpt['id'])) $tlab = $labOpt['id'];
			if (isset($labOpt['nnr_id'])) $tlab = $labOpt['nnr_id'];
			
			if ($tlab == $labId && $labOpt['lab-id'] == 129) {	

		?>
		<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
		<h3><?php echo $labOpt['name'];?> <?php echo $labOpt['address'];?><br>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</h3>
		
		<?php 
		
			break;
		
		} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
		<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
		<h3><?php echo $labOpt['name'];?> <br>>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</h3>
		
		<?php		
		
			}
			
		}
	
		?>
					
		<?php } else if ($state && !Mage::helper('medivo')->isNNRState($state) &&  $labId =  Mage::getSingleton('core/session')->getLabId()){
			
				foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
					
					if (isset($labOpt['id'])) $tlab = $labOpt['id'];
					if (isset($labOpt['nnr_id'])) $tlab = $labOpt['id'];
					
					if ($tlab == $labId && $labOpt['lab-id'] == 129) {	
		
		?>
				<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
				<h3><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</h3>
				
		
		<?php		} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
				<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
				<h3><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</h3> 

				
		<?php		}
					
				}
		
		} else if ($state && !Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>
		
			<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
			<h3>We have 6+ testing locations near you. Select your preferred location during checkout.</h3>
		
		<?php }  else if ($state && Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>

			<a style="color:#028AFB; font-weight:bold;" href="/locate-testing-center">Update Location</a>
			<h3>We have 6+ testing locations near you. However, pricing varies due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>. Proceed to checkout to identify your preferred location and view local pricing.</h3>

		<?php } else { ?>
			
			<h3>For test availability and local pricing,<br />
                    please enter your zip code</h3>
			
		<?php } ?>                    
        
    </div>
                  
    <div style="clear:both;"></div> 
	
	<h2>2. Select STD tests:</h2>
	
	<div id="order_module">
	<form name="orderWidget" id="orderWidget" method="post" action="/customroute/index/checkout">
	
		<div id="at_home">
			<div class="header">At-Home Testing</div>
			<div class="content">
			<h4><span class="light_blue">Free priority shipping</span></h4>
				<ul>
					<li> 
						<input type="checkbox" value="<?php echo $_products['at-home-STD-testing-for-women']['price'];?>" id="at-home-STD-testing-for-women" onClick="updateWidgetTotal(this.id,<?php echo $_products['at-home-STD-testing-for-women']['id'];?>);toggleCartElement(this.id);" name="homeTest[at-home-STD-testing-for-women]" />
						<div class="text">
						<p>At-Home STD Testing for Women</p>
						<p class="small">(Chlamydia, Gonorrhea, Trichomoniasis)</p>
						</div>
						<div class="price">$289</div>
					</li>
					<li> 
						<input type="checkbox" value="<?php echo $_products['at-home-STD-testing-for-men']['price'];?>" id="at-home-STD-testing-for-men" onClick="updateWidgetTotal(this.id,<?php echo $_products['at-home-STD-testing-for-men']['id'];?>);toggleCartElement(this.id);" name="homeTest[at-home-STD-testing-for-men]" />
						<div class="text">
						<p>At-Home STD Testing for Men</p>
						<p class="small">(Chlamydia, Gonorrhea, Trichomoniasis)</p>
						</div>
						<div class="price">$289</div>
					</li>
					<li> 
						<input type="checkbox" value="<?php echo $_products['hiv-home']['price'];?>" id="hiv-home" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-home']['id'];?>);toggleCartElement(this.id);" name="homeTest[hiv-home]" />
						<div class="text">
						<p>At-Home HIV Test</p>
						</div>
						<div class="price">$99</div>
					</li>
				</ul>
			</div>
		</div><!-- /at_home -->
		
		<div class="sep">OR</div>
		
		<div id="lab_tests">
			<div class="header">Local, Private Lab Testing</div>
			<div id="individual_tests" class="item">
			<h4>Individual Tests</h4>
				<table>
				<tbody>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['chlamydia-lab']['price'];?>" id="chlamydia-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['chlamydia-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[chlamydia-lab]" /> Chlamydia</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['gonorrhea-lab']['price'];?>" id="gonorrhea-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['gonorrhea-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[gonorrhea-lab]" /> Gonorrhea</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['hepatitis-b-lab']['price'];?>" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-b-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" /> Hepatitis B</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['hepatitis-c-lab']['price'];?>" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hepatitis-c-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" /> Hepatitis C</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['oralherpes-lab']['price'];?>" id="oralherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['oralherpes-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[oralherpes-lab]" /> Oral Herpes</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['genitalherpes-lab']['price'];?>" id="genitalherpes-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['genitalherpes-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[genitalherpes-lab]" /> Genital Herpes</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['hiv-lab']['price'];?>" id="hiv-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['hiv-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[hiv-lab]" /> HIV</td>
						<td class="price">$89</td>
					</tr>
					<tr>
						<td><input type="checkbox" value="<?php echo $_products['syphilis-lab']['price'];?>" id="syphilis-lab" onClick="updateWidgetTotal(this.id,<?php echo $_products['syphilis-lab']['id'];?>);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" /> Syphilis</td>
						<td class="price">$89</td>
					</tr>
				</tbody>
				</table>
				<span style="display:none;"><input type="radio" id="indi_tests" value="0" onClick="updateWidgetTotal(this.id,0);" name="testType" /></span>
			</div><!-- /individual_tests -->
		
			<div id="ultimate_package" class="item">
				<div class="content">
				<h4>Ultimate Package</h4>
					<ul>
						<li>Chlamydia</li>
						<li>Gonorrhea</li>
						<li>Hepatitis B</li>
						<li>Hepatitis C</li>
						<li>Oral Herpes</li>
						<li>Genital Herpes</li>
						<li>HIV</li>
						<li>Syphilis</li>
					</ul>
				</div>
				<div class="footer">
					<div class="price">$249</div>
					<div class="add_to_cart"><input type="radio" id="complete_package" value="<?php echo $_products['ultimate-8-pack-package-lab']['price'];?>" onClick="updateWidgetTotal(this.id,<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>);toggleCartElement(this.id);" name="testType" /> Add to cart</div>
					<input id="complete_package_hidden" type="hidden" value="<?php echo $_products['ultimate-8-pack-package-lab']['price'];?>" name="pack_<?php echo $_products['ultimate-8-pack-package-lab']['id'];?>">
				</div>
			</div><!-- /ultimate_package -->
		</div><!-- /lab_tests -->
		
		<div class="sep sep_arrow">&nbsp;</div>
		
		<div id="your_order">
			<div class="header">Your Order</div>
			<div class="content">
				<div id="ow_list">
                                	
                 <div style="display:none;" id="chlamydia-home-cart">&bull;&nbsp;Chlamydia</div>
                 <div style="display:none;" id="gonorrhea-home-cart">&bull;&nbsp;Gonorrhea</div>
                 <div style="display:none;" id="trichomoniasis-home-cart">&bull;&nbsp;Trichomoniasis</div>
                 <div style="display:none;" id="hiv-home-cart">&bull;&nbsp;HIV Express</div>
                 
                 <div style="display:none;" id="chlamydia-lab-cart">&bull;&nbsp;Chlamydia</div>
                 <div style="display:none;" id="gonorrhea-lab-cart">&bull;&nbsp;Gonorrhea</div>
                 <div style="display:none;" id="hepatitis-b-lab-cart">&bull;&nbsp;Hepatitis B</div>
                 <div style="display:none;" id="hepatitis-c-lab-cart">&bull;&nbsp;Hepatitis C</div>
                 <div style="display:none;" id="oralherpes-lab-cart">&bull;&nbsp;Oral Herpes</div>
                 <div style="display:none;" id="genitalherpes-lab-cart">&bull;&nbsp;Genital Herpes</div>
                 <div style="display:none;" id="hiv-lab-cart">&bull;&nbsp;HIV</div>
                 <div style="display:none;" id="syphilis-lab-cart">&bull;&nbsp;Syphilis</div>
                 
                 
                 
                 <div id="complete_package-cart" style="display:none;">
                 <div id="chlamydia-lab-cart-cp">&bull;&nbsp;Chlamydia</div>
                 <div id="gonorrhea-lab-cart-cp">&bull;&nbsp;Gonorrhea</div>
                 <div id="genitalherpes-lab-cart-cp">&bull;&nbsp;Genital Herpes</div>
                 <div id="hiv-lab-cart-cp">&bull;&nbsp;HIV</div>
                 </div>
                 
                 <div id="expert_package-cart" style="display:none;">
                 <div id="chlamydia-lab-cart-ep">&bull;&nbsp;Chlamydia</div>
                 <div id="gonorrhea-lab-cart-ep">&bull;&nbsp;Gonorrhea</div>
                 <div id="hepatitis-b-lab-cart-ep">&bull;&nbsp;Hepatitis B</div>
                 <div id="hepatitis-c-lab-cart-ep">&bull;&nbsp;Hepatitis C</div>
                 <div id="oralherpes-lab-cart-ep">&bull;&nbsp;Oral Herpes</div>
                 <div id="genitalherpes-lab-cart-ep">&bull;&nbsp;Genital Herpes</div>
                 <div id="hiv-lab-cart-ep">&bull;&nbsp;HIV</div>
                 <div id="syphilis-lab-cart-ep">&bull;&nbsp;Syphilis</div>
                 </div>
                 
                             	
                                	</div>
			</div>
			<hr />
			<div class="total"><div id="widget_total" style="width:145px;float:left;">Select Tests</div><input class="submit btn_orange" type="submit" onclick="checkEmpty();" value="checkout" /></div>
		</div><!-- /your_order --> 
	<input type="hidden" id="package" name="package" value="">
	</form>
	</div><!-- /order_module -->
	
	<div class="clear">&nbsp;</div>
</div><!-- /order_wide_content -->
