<?php

	//echo "<pre>";  print_r(Mage::getModel('core/session')->getData()); echo "</pre>";

	//$this = new Jag_Orderwidget_Block_Orderwidget;

	// echo get_class($this);

	$this->resetCart();



	$_products = $this->getProducts();

	$state = Mage::getSingleton('core/session')->getOrderState();

	$sZip = Mage::getSingleton('core/session')->getZip();

	if ($sZip) {
		$sesZip = $sZip;
	} else {
		$sesZip = 'Zip Code';
	}

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Get STD Tested</title>

	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/lp/03/css/styles.css" type="text/css" media="all" />
	<link rel="shortcut icon" href="/lp/03/images/favicon.ico" />

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />

	<meta name="robots" content="all" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	
	<script type="text/javascript" src="/js/prototype/prototype.js"></script>
	<script type="text/javascript" src="/js/lib/ccard.js"></script>
	<script type="text/javascript" src="/js/prototype/validation.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/builder.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/effects.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/dragdrop.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/controls.js"></script>
	<script type="text/javascript" src="/js/scriptaculous/slider.js"></script>

	<script type="text/javascript" src="/js/varien/js.js"></script>
	<script type="text/javascript" src="/js/varien/form.js"></script>
	<script type="text/javascript" src="/js/varien/menu.js"></script>
	<script type="text/javascript" src="/js/mage/translate.js"></script>
	<script type="text/javascript" src="/js/mage/cookies.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/main.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/getstdtested/js/SpryAccordion.js"></script>
	<script type="text/javascript" src="/skin/frontend/default/default/js/enterprise/catalogevent.js"></script>

	<script type="text/javascript" src="/skin/frontend/default/default/js/opcheckout.js"></script>
	
	<!-- Google Website Optimizer Tracking Script -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['gwo._setAccount', 'UA-10462432-2']);
	  _gaq.push(['gwo._trackPageview', '/4061259124/test']);
	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<!-- End of Google Website Optimizer Tracking Script -->
		
	<script type="text/javascript">
	//<![CDATA[
	Mage.Cookies.path     = '/';
	Mage.Cookies.domain   = '.getstdtested.com';
	//]]>
	</script>

	<script type="text/javascript">
	//<![CDATA[
	optionalZipCountries = [];
	//]]>
	</script>

</head>

<body>
	
	
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
	
	if (document.getElementById('zip_code').value.length != 5 ||is_int(document.getElementById('zip_code').value) === false) {			
	//if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder",array('_secure'=>false)) ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;

var ultimatePackage = 229;

var indiSkuArr = new Array();
	indiSkuArr[0] = 'hiv-lab';
	indiSkuArr[1] = 'chlamydia-gonorrhea-lab';
	indiSkuArr[2] = 'oral-genital-herpes-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'hepatitis-b-lab';
	indiSkuArr[5] = 'hepatitis-c-lab';
	indiSkuArr[6] = 'hiv-early-detection-lab';

var indiTestOrig = new Array();
	indiTestOrig[0] = 79;
	indiTestOrig[1] = 149;
	indiTestOrig[2] = 149;
	indiTestOrig[3] = 89;
	indiTestOrig[4] = 89;
	indiTestOrig[5] = 89;
	indiTestOrig[6] = 179;
	
	var homeSkuArr = new Array();
	homeSkuArr[0] = 'hiv-home';
	homeSkuArr[1] = 'chlamydia-gonorrhea-home';
	homeSkuArr[2] = 'trichomoniasis-home';
	
var homeTestOrig = new Array();
	homeTestOrig[0] = 99;
	homeTestOrig[1] = 149;
	homeTestOrig[2] = 199;
	
	
	
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		if (document.getElementById('hiv-early-detection-lab').checked == false) {
	
			total = 0;
			
			price = 0;
			
			cartArr = new Array();
		
		} else {
		
			total = 0;
		
			price = indiTestOrig[6];
				
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
		
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = parseInt(document.getElementById(el).value) + price;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 99;
    			
    			}
			}
	   	
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true && document.getElementById('hiv-early-detection-lab').checked == true) {
	
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('hiv-early-detection-lab').checked = false;
			
			document.getElementById('hiv-early-detection-lab').value = indiTestOrig[6];
			
			document.getElementById('package').value = "";
			
			total = 0;
		
		}
		
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
			
		}
		
		/*
if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').value < 0) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
		
		}
*/
		
	
		
		
	
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {
					
			for (i = 0; i < homeSkuArr.length; i++) {
			
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
					
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
		
		if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').checked == false) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
			
			total = total + price;
		
		} else {
		
		total = total + price;
		
		}
		
			
	   	
	   	   
	
	   document.getElementById('widget_total').innerHTML = '$'+(total);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'expert_package') {
		
		//document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			//document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			//document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	
	//document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	/*
if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
*/
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>

<div id="wrap">

	<div id="canvas">

		<div id="header">
			<div id="logo"><a href="#" title="Home | Get STD Tested">Get STD Tested</a></div>
			<div class="phone">855-287-6195</div>
		</div>

		<div id="headline">
			<h1>19 Million Americans have an STD. You're not alone.</h1>
		</div>

		<div id="banner">
			<h2>Don't let an STD stop you from living your life. Get tested so you can get on with your life.</h2>
			<h3>Fast | Convenient | Hospital-Accurate | 100% PRIVATE</h3>
			<div id="b-get-tested"><a href="#get-tested" title="Click here and take control of your life!">Click here and take control of your life!</a></div>
		</div>
		
		<br />
		<hr />

		<div id="callouts">
			<div class="col6">
				<h4>Complete Privacy</h4>
				<p>No insurance reporting. No undressing. STD testing and results are completely private.</p>
			</div>
			<div class="col6">
				<h4>Accurate Tests</h4>
				<p>Most accurate tests on the market. Same STD tests administered by doctors and hospitals nationwide.</p>
			</div>
			<div class="col6">
				<h4>Test Today</h4>
				<p>Test today at 4,000+ local facilities open until 5:00pm or later - no appointment needed. At home STD testing also available.</p>
			</div>
			<div class="col6">
				<h4>Quick Results</h4>
				<p>Trusted results within three days - faster than a doctor's office.</p>
			</div>
			<div class="col6">
				<h4>Doctor Consult</h4>
				<p>On-staff physicians available free-of-charge to help interpret test results and answer questions.</p>
			</div>
			<div class="col6">
				<h4>Get Treated</h4>
				<p>On-staff physicians prescribe treatment for curable STDs. No appointment needed.</p>
			</div>
		</div>
		
		<br />
		<hr />

		<h3>DON'T TAKE OUR WORD FOR IT. LISTEN TO OUR SATISFIED CUSTOMERS:</h3>
		<div id="testimonials">
			<div class="col3">
				<p>
					<img src="/lp/03/images/testimonial-photo-01.jpg" width="96" height="96" alt="" border="0" align="left" />
					"The process was completely thorough, quick, fast, and everything was great. It was everything I was looking for in this type of situation."<br />
					<span>Mark W. from Ohio</span>
				</p>
			</div>
			<div class="col3">
				<p>
					<img src="/lp/03/images/testimonial-photo-02.jpg" width="96" height="96" alt="" border="0" align="left" />
					"My doctor wouldn't have been able to see me for 2 months. I was able to get same day testing through your service and my test results came back sooner than 3 days."<br />
					<span>Male, 36 from Illinois</span>
				</p>
			</div>
			<div class="col3">
				<p>
					<img src="/lp/03/images/testimonial-photo-03.jpg" width="96" height="96" alt="" border="0" align="left" />
					"I would recommend you and I will use your services again. I appreciate the convenience, confidentiality, and ease with which the tests are conducted."<br />
					<span>Laura R. from Texas</span>
				</p>
			</div>
			<p class="acenter">
				<img src="/lp/03/images/ratings.gif" width="225" height="48" alt="" border="0" /><br />
				4.5 out of 5 star customer reviews
			</p>
		</div>
		
		<hr />

		<h3>FOLLOW OUR FOUR EASY STEPS TO GOOD SEXUAL HEALTH:</h3>

		<div id="how-it-works">
			<p>1. Order</p>
			<p>2. Test</p>
			<p>3. Results</p>
			<p>4. Treat</p>
		</div>
		
		<a name="get-tested"></a>

		<div id="order">

			<h2 class="fleft"><strong>Enter ZIP code to see which tests are available in your area:</strong></h2>

			<form onsubmit="return false;" id="location_form">
				<input type="text" onKeyPress="return submitenter(event);" class="text" id="zip_code" name="zip_code" value="Enter Zip Code" maxlength="5" onfocus="javascript: if(this.value == 'Enter Zip Code') this.value = '';" onblur="javascript: if(this.value == '') this.value = 'Enter Zip Code';" />
				<input id="location_submit_button" class="b-submit" type="button" onClick="handlerFunction();return false;" value="Submit" /><br />
				<img style="display: none; float: right; margin: 7px 0 0 0;" id="ajax-loader-gif" src="http://getstdtested.com/media/images/ajax-loader.gif" />
			</form>
			
			<div id="location_results">
		
			<?php if ($state && Mage::helper('medivo')->isNNRState($state) && $labId =  Mage::getSingleton('core/session')->getLabId()) { ?>
				
				<?php 
					foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
						
						$labOpt = (array)$labOpt;
						
						if (isset($labOpt['id'])) $tlab = $labOpt['id'];
						if (isset($labOpt['nnr_id'])) $tlab = $labOpt['nnr_id'];
						
						if ($tlab == $labId && $labOpt['lab-id'] == 129) {	
			
					?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <?php echo $labOpt['address'];?><br>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</strong>
					</p>
					
					<?php 
					
						break;
					
					} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong><?php echo $labOpt['name'];?> <br>Due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>, pricing and test options vary by state.  Pricing will be verified after selecting products and clicking checkout. To continue, select STD tests below.</strong>
					</p>
					
					<?php		
					
						}
						
					}
				
				?>

				<?php } else if ($state && !Mage::helper('medivo')->isNNRState($state) &&  $labId =  Mage::getSingleton('core/session')->getLabId()){
					
						foreach (Mage::getSingleton('core/session')->getLabsByZip() as $labOpt) {
							
							if (isset($labOpt['id'])) $tlab = $labOpt['id'];
							if (isset($labOpt['nnr_id'])) $tlab = $labOpt['id'];
							
							if ($tlab == $labId && $labOpt['lab-id'] == 129) {	
				
				?>
						<p>
							<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
							<strong><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</strong>
						</p>
						
				
				<?php		} else if  ($tlab == $labId && $labOpt['lab-id'] == 119) { ?>
						<p>
							<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
							<strong><?php echo $labOpt['name'];?> <br> Select your STD tests below and verify or update this location during checkout.</strong>
						</p>
						
				<?php		}

						}

				} else if ($state && !Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>

					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong>We have 6+ testing locations near you. Select your preferred location during checkout.</strong>
					</p>
				
				<?php }  else if ($state && Mage::helper('medivo')->isNNRState($state) && !Mage::getSingleton('core/session')->getLabId()) { ?>

					<p>
						<a style="color:#028AFB; font-weight:bold;" href="http://getstdtested.com/locate-testing-center">Update Location</a><br />
						<strong>We have 6+ testing locations near you. However, pricing varies due to state regulations in <?php echo Mage::helper('medivo')->getNnrStatesString() ?>. Proceed to checkout to identify your preferred location and view local pricing.</strong>
					</p>

				<?php } else { ?>
					
					<p><strong>For test availability and local pricing, please enter your zip code.</strong></p>
					
				<?php } ?>
			
			</div>

			<h3 class="cboth">NOW SELECT YOUR TESTS:</h3>
			
			<div id="order_module"> 
				<form name="orderWidget" id="orderWidget" method="post" action="http://getstdtested.com/customroute/index/checkout">

					<div id="at_home">
						<div class="header">At-Home Testing</div>
						<div class="content">
							<h4><strong>Free</strong> Priority Shipping</h4>
							<ul>
								<li><input type="checkbox" value="99.0000" id="hiv-home" onClick="updateWidgetTotal(this.id,4);toggleCartElement(this.id);" name="homeTest[hiv-home]" /><label for="hiv-home">HIV Standard</label></li>
								<li class="price">$99</li>
								<li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="149.0000" id="chlamydia-gonorrhea-home" onClick="updateWidgetTotal(this.id,44);toggleCartElement(this.id);" name="homeTest[chlamydia-gonorrhea-home]" /><label for="chlamydia-gonorrhea-home">Chlamydia &amp; Gonorrhea</label></li>
								<li class="price">$149</li>
								<li><input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="199.0000" id="trichomoniasis-home" onClick="updateWidgetTotal(this.id,3);toggleCartElement(this.id);" name="homeTest[trichomoniasis-home]" /><label for="trichomoniasis-home">Trichomoniasis</label></li>
								<li class="price">$199</li>
							</ul>
						</div>
					</div> <!-- /at_home -->
					
					<div id="lab_tests">
					
						<div class="header">Local Lab Testing</div>
						
						<div class="item" id="individual_tests">
							<div class="content">
								<h4>Individual Tests</h4>
								<ul>                  	
									<li><input type="checkbox" value="79.0000" id="hiv-lab" onClick="updateWidgetTotal(this.id,11);toggleCartElement(this.id);" name="indiTest[hiv-lab]" /><label for="hiv-lab">HIV Standard</label></li>
									<li class="price">$79</li>
									<li><input type="checkbox" value="149.0000" id="chlamydia-gonorrhea-lab" onClick="updateWidgetTotal(this.id,40);toggleCartElement(this.id);" name="indiTest[chlamydia-gonorrhea-lab]" /><label for="chlamydia-gonorrhea-lab">Chlamydia &amp; Gonorrhea</label></li>
									<li class="price">$149</li>
									<li><input type="checkbox" value="149.0000" id="oral-genital-herpes-lab" onClick="updateWidgetTotal(this.id,42);toggleCartElement(this.id);" name="indiTest[oral-genital-herpes-lab]" /><label for="oral-genital-herpes-lab">Oral &amp; Genital Herpes</label></li>
									<li class="price">$149</li>
									<li><input type="checkbox" value="89.0000" id="syphilis-lab" onClick="updateWidgetTotal(this.id,12);toggleCartElement(this.id);" name="indiTest[syphilis-lab]" /><label for="syphilis-lab">Syphilis</label></li>
									<li class="price">$89</li>
									<li><input type="checkbox" value="89.0000" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,7);toggleCartElement(this.id);" name="indiTest[hepatitis-b-lab]" /><label for="hepatitis-b-lab">Hepatitis B</label></li>
									<li class="price">$89</li>
									<li><input type="checkbox" value="89.0000" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,8);toggleCartElement(this.id);" name="indiTest[hepatitis-c-lab]" /><label for="hepatitis-c-lab">Hepatitis C</label></li>
									<li class="price">$89</li>
									<li><input type="checkbox" <?php if (Mage::getSingleton('core/session')->getLabType() == 119) { ?> disabled="disabled" <?php } ?> value="179.0000" id="hiv-early-detection-lab" onClick="updateWidgetTotal(this.id,13);toggleCartElement(this.id);" name="indiTest[hiv-early-detection-lab]" /><label for="hiv-early-detection-lab">HIV Early Detection *</label></li>
									<li class="price">$179</li>
								</ul>
							</div>
						</div> <!-- /individual_tests -->
						
						<div class="item" id="ultimate_package">
							<div class="content">
								<h4><strong>Best Value Pack</strong></h4>
								<ul>                   	
									<li>HIV Standard</li>
									<li>Chlamydia</li>
									<li>Gonorrhea</li>
									<li>Oral Herpes</li>
									<li>Genital Herpes</li>
									<li>Syphilis</li>
									<li>Hepatitis B</li>
									<li>Hepatitis C</li>
								</ul>
								<div class="cboth"></div>
							</div>
							<div class="footer">
							<div class="add_to_cart">
								<input type="radio" id="expert_package" value="229" onClick="updateWidgetTotal(this.id,14);toggleCartElement(this.id);" name="testPackage" />
								<label for="expert_package">Add to cart</label>
								<input id="expert_package_hidden" type="hidden" name="pack_14" value="229">
							</div>
								<div class="price">
									$229 <span>for</span> 8 Tests
								</div>
							</div>
						</div> <!-- /ultimate_package -->
						
					</div> <!-- /lab_tests -->
					
					<div id="your_order">
						<div class="header">Order Total</div>
							
						<div class="total">
							&nbsp; <span id="total_price"><div id="widget_total">$0</div></span>
						</div>
						<input type="button" onclick="checkEmpty();" class="submit btn_orange_32_reflection" value="checkout" style="width: 125px;" />
					</div> <!-- /your_order -->
					<input type="hidden" id="package" name="package" value="">          
				</form>
				<div class="cboth"></div>
			</div> <!-- /order_module -->
				
		</div>
		<div class="cboth">&nbsp;</div>
		
		<br />
		<hr />

		<h3>IN ADDITION TO OUR CUSTOMERS AND THE SEXUAL HEALTH COMMUNITY, WE ARE SUPPORTED BY:</h3>

		<div id="trustbuilders"></div>

		<div class="phone">855-287-6195</div>

		<div class="cboth"><br /><br /></div>
		
	</div>

</div>


<!-- Google Code for GST Visitors 1 Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1047469408;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "666666";
var google_conversion_label = "w3GLCNrD9AEQ4Lq88wM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1047469408/?label=w3GLCNrD9AEQ4Lq88wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- End of Google Code for GST Visitors 1 Remarketing List -->

<!-- Start of Zopim Live Chat Script -->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=
z.s=d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o
){z.set._.push(o)};$.setAttribute('charset','utf-8');$.async=!0;z.set.
_=[];$.src=('https:'==d.location.protocol?'https://ssl':'http://cdn')+
'.zopim.com/?uBwYwCVwg065nQ32d19kYDqQ6a1l91wt';$.type='text/java'+s;z.
t=+new Date;z._=[];e.parentNode.insertBefore($,e)})(document,'script')
</script>
<!-- End of Zopim Live Chat Script -->

<!-- Begin adBrite, important page views tracking -->
<img src="http://bstats.adbrite.com/adserver/behavioral-data/0?d=47384704;bapid=10251;uid=845986" border="0" hspace="0" vspace="0" width="1" height="1"/> 
<!-- End adBrite, important page views tracking -->

<!-- AdRoll Remarketing Code -->
<script type="text/javascript">
adroll_adv_id = "OBD5PEJZNRCB3PQUJMOZ65";
adroll_pix_id = "V6VV7AXHKZHE3JSOL2EKB5";
(function () {
var oldonload = window.onload;
window.onload = function(){
   __adroll_loaded=true;
   var scr = document.createElement("script");
   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
   scr.setAttribute('async', 'true');
   scr.type = "text/javascript";
   scr.src = host + "/j/roundtrip.js";
   ((document.getElementsByTagName('head') || [null])[0] ||
	document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
   if(oldonload){oldonload()}};
}());
</script>
<!-- EOF AdRoll Remarketing Code -->


</body>
</html>

