<?php
    $wellness_package = $this->getWellnessPackageProduct();
    $wellness_package_sku = $wellness_package->getSku();
    $wellness_package_id = $wellness_package->getEntityId();
?>

<h1 style="padding-top: 24px; font-family: arial; font-size: 28px; line-height: 42px;">Add wellness testing to your order now.</h1>
<h2 style="margin-bottom: 5px; color: #777; font-family: arial;">You're already at the lab. Test your complete health while you're there.</h2>

<form id="onestepcheckout-upsell-form" method="post" action="<?php echo $this->getUpsellPostActionUrl() ?>">

<div id="checkout_location" class="box">
    <div class="onestepcheckout-header">
        <h2 id="onestepcheckout-wellness-tests">Select Testing Options</h2>
    </div>
    <div id="wellness-tests">

        <input type="checkbox" name="indiTest[<?php echo $wellness_package_sku ?>]" id="<?php echo $wellness_package_sku ?>" onclick="toggleUpsellCartElement('<?php echo $wellness_package_sku ?>');" value="<?php echo $wellness_package->getPrice() ?>" />
        <h1><label for="<?php echo $wellness_package_sku ?>">Complete Checkup Panel</label></h1>
        <span class="price-pack-old">$<?php echo intval($wellness_package->getUpsellOldPrice()) ?></span>
        <span class="price-pack">$<?php echo intval($wellness_package->getPrice()) ?></span>
        <p><?php echo $wellness_package->getDescription() ?></p>
        <ul class="fleft">
            <li>Diabetes</li>
            <li>Liver</li>
        </ul>
        <ul class="fleft">
            <li>Lipid</li>
            <li>Thyroid</li>
        </ul>

        <h2>Individual Tests</h2>

        <?php  $first_product = true; ?>
        <?php foreach ($this->getOnlyIndivdualUpsellProducts() as $product) { ?>
            <?php $product_sku = $product->getSku(); ?>
            <div class="<?php if ($first_product) { echo "cboth"; $first_product = false; } ?> wellness-tests-col">
                <input type="checkbox" name="indiTest[<?php echo $product_sku ?>]" id="<?php echo $product_sku ?>" onclick="toggleUpsellCartElement('<?php echo $product_sku ?>');" value="<?php echo $product->getPrice() ?>" />
                <h3><label for="<?php echo $product_sku ?>"><?php echo $product->getName() ?></label></h3>
                <span class="price-pack-old">$<?php echo intval($product->getUpsellOldPrice()) ?></span>
                <span class="price-pack">$<?php echo intval($product->getPrice()) ?></span>
                <p><?php echo $product->getDescription() ?></p>
            </div>
        <?php } ?>
        <div class="cboth"></div>

    </div>
</div>

    <ul class="one-step-checkout">

        <li class="address-order">

            <div id="left-info">

                <div id="order-button-div">
                    <div class="content button-set clearfix" style="width: 700px;">
                        <p>
                            <input id="onestepcheckout-button-place-order" type="button" class="btn_orange_reflection" style="margin: 0 auto 30px auto; border:none;" onclick="this.disabled=true;document.getElementById('ajax-loader-gif').style.display = 'block';document.getElementById('onestepcheckout-upsell-form').submit();_gaq.push(['_trackEvent', 'Upsells - Upgrade', 'Click', '']);" value="Upgrade Order" />
                            <img style="display:none; float:left; margin-left:20px; margin-top:1%;" id="ajax-loader-gif" src="http://getstdtested.com/media/images/ajax-loader.gif" />
                        </p>
                        <p class="cboth"><a href="<?php echo $this->getNoThanksAction() ?>" onclick="_gaq.push(['_trackEvent', 'Upsells - No thanks', 'Click', '<?php echo $this->getNoThanksAction() ?>']);" style="color: #028AFB; font-size: 14px; font-weight: bold; text-decoration: underline;">No, thanks. Continue to checkout.</a></p>
                    </div>
                </div>

            </div>

        </li>

    </ul>
</form>
