<?php

$this->resetCart();

$_products = $this->getProducts();

?>
<script type="text/javascript">

function is_int(value){
   for (i = 0 ; i < value.length ; i++) {
      if ((value.charAt(i) < '0') || (value.charAt(i) > '9')) return false 
    }
   return true;
}

function handlerFunction(){
	
	document.getElementById('ajax-loader-gif').style.display = 'block'; 
				
	if ($("zip_code").value.length != 5 ||is_int($("zip_code").value) === false) {
		
		alert('Please enter a valid 5 digit zip code.');
		document.getElementById('ajax-loader-gif').style.display = 'none'; 
		return false;
		
	}
		
	
 
        var request = new Ajax.Request(
            '<?php echo $this->getUrl("medivo/local/getlabsorder") ?>',
            {
                method: 'post',
                onComplete: function(transport){ 
 
                    var jsonResponse=transport.responseText;

                    if(jsonResponse.error){
                        alert("Error Occured");
                        return false;
                    }
                    else{
                    	document.getElementById('ajax-loader-gif').style.display = 'none';
                        document.getElementById("location_results").innerHTML =jsonResponse;
                    }
                },
                parameters: Form.serialize($("location_form"))            
           }
        );
}


var basicPackage = 150;

var ultimatePackage = 229;

var indiSkuArr = new Array();
	indiSkuArr[0] = 'hiv-lab';
	indiSkuArr[1] = 'chlamydia-gonorrhea-lab';
	indiSkuArr[2] = 'oral-genital-herpes-lab';
	indiSkuArr[3] = 'syphilis-lab';
	indiSkuArr[4] = 'hepatitis-b-lab';
	indiSkuArr[5] = 'hepatitis-c-lab';
	indiSkuArr[6] = 'hiv-early-detection-lab';

var indiTestOrig = new Array();
	indiTestOrig[0] = 79;
	indiTestOrig[1] = 149;
	indiTestOrig[2] = 149;
	indiTestOrig[3] = 89;
	indiTestOrig[4] = 89;
	indiTestOrig[5] = 89;
	indiTestOrig[6] = 179;
	
	var homeSkuArr = new Array();
	homeSkuArr[0] = 'hiv-home';
	homeSkuArr[1] = 'chlamydia-gonorrhea-home';
	homeSkuArr[2] = 'trichomoniasis-home';
	
var homeTestOrig = new Array();
	homeTestOrig[0] = 105;
	homeTestOrig[1] = 165;
	homeTestOrig[2] = 205;
	
	
	
	
var cartArr = new Array();
	

function updateWidgetTotal(el,id) {
		
	if (typeof total == 'undefined') {
		
		total = 0;
	
	}
	
	var discount = 0;
	
	if (document.getElementById(el).type == 'radio') {
	
	
		if (document.getElementById('hiv-early-detection-lab').checked == false) {
	
			total = 0;
			
			price = 0;
			
			cartArr = new Array();
		
		} else {
		
			total = 0;
		
			price = indiTestOrig[6];
				
		}
		
		<?php if (!Mage::getSingleton('core/session')->getIsNnr()) { ?>
		
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	
		if (document.getElementById(el).value == 0) {
	
			document.getElementById('widget_total').innerHTML = "Select Tests";
			
		} else {
		
			price = parseInt(document.getElementById(el).value) + price;
	
			price = parseInt(price);
		
			document.getElementById('widget_total').innerHTML = "$"+price;	
			
			if (el == 'complete_package') {
			
				document.getElementById('complete_package_hidden').value = price;
				document.getElementById('expert_package_hidden').value = 0;
			
			} else {
			
				document.getElementById('expert_package_hidden').value = price;
			
			}
		
		}
		
		<?php } else  { ?>
			
		document.getElementById('package').value = id;
	
		for (i = 0; i < indiSkuArr.length; i++) {
			
			if (indiSkuArr[i] != 'hiv-early-detection-lab') {
		
			document.getElementById(indiSkuArr[i]).checked = false;
			document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
			
			}
			
		}
			
		for (i = 0; i < homeSkuArr.length; i++) {
			document.getElementById(homeSkuArr[i]).checked = false;
			document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
		}
	   	
	   	total = 125;
	   	
	   	for (var i = 0; i < cartArr.length; i++) {
    			
    			if (cartArr[i] == 'hiv-home'){
    			
    				total = 105;
    			
    			}
			}
	   	
	   	
	   	document.getElementById('widget_total').innerHTML = '$'+total;
	   	
	   <?php } ?>
	
	   
		
	} else {
		
		re = 0;
	
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true && document.getElementById('hiv-early-detection-lab').checked == true) {
	
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('hiv-early-detection-lab').checked = false;
			
			document.getElementById('hiv-early-detection-lab').value = indiTestOrig[6];
			
			document.getElementById('package').value = "";
			
			total = 0;
		
		}
		
		if (el != 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
			
		}
		
		/*
if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').value < 0) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
		
		}
*/
		
		price = document.getElementById(el).value;
	
		price = parseInt(price);

		if(el.indexOf('home')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('lab')>0) {
								
				 	//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if(el.indexOf('lab')> 0) {
		
			for (i = 0; i < cartArr.length; i++) { 
			
				if (cartArr[i].indexOf('home')>0) {
				
					//document.getElementById(cartArr[i]+"-cart").style.display = "none";
				
					re = 1;
				
				}
			
			}
		
		}
		
		if (re == 1) {
		
			cartArr = new Array();
		
		}
				
		if (indiSkuArr.indexOf(el) >= 0) {		
					
			for (i = 0; i < homeSkuArr.length; i++) {
			
				if (document.getElementById(homeSkuArr[i]).checked == true) {
					document.getElementById(homeSkuArr[i]).checked = false;
					document.getElementById(homeSkuArr[i]).value = homeTestOrig[i];
					total = 0;
				}
			}
		
		} else {		
		
			document.getElementById('expert_package_hidden').value = 0;
		
			document.getElementById('expert_package').checked = false;
			
			document.getElementById('package').value = "";
							
			for (i = 0; i < indiSkuArr.length; i++) {
				if (document.getElementById(indiSkuArr[i]).checked == true) {
					document.getElementById(indiSkuArr[i]).checked = false;
					document.getElementById(indiSkuArr[i]).value = indiTestOrig[i];
					total = 0;
				}
			}
		
		}
	
		if (price < 0) {
		
			document.getElementById(el).value = price + (price*-2);
			
			for (key in cartArr) {
    			if (cartArr[key] == el) {
        			cartArr.splice(key, 1);
    			}
			}
			
				
		} else {
		
			document.getElementById(el).value = price - (price*2);
			
			cartArr.push(el);
	
		}
		
			
	  if (el == 'hiv-early-detection-lab' && document.getElementById('expert_package').checked == true) {
		
			if (document.getElementById('hiv-early-detection-lab').checked == false) {	
					
				total = 418;
				
			} else {
			
				total = 229;
			
			}
			
			total = total + price;
		
		} else {
		
		total = total + price;
		
		}
	   
	
	   document.getElementById('widget_total').innerHTML = '$'+(total);
	
	}
	
}

function checkEmpty() {
	
	if (cartArr.length == 0 && !document.getElementById('expert_package').checked) {
		
		alert('Please select STD tests before checkout.');
		
		return false;
		
	}
	
	
	
	document.getElementById('orderWidget').submit();
	return true;
	
}

function turnOff (el){

	

}

function toggleCartElement(el) {

	if (el == 'expert_package') {
		
		document.getElementById('expert_package-cart').style.display = 'block';
		
		for (i = 0; i < indiSkuArr.length; i++) {
			//document.getElementById(indiSkuArr[i]+'-cart').style.display = "none";
		}
		
		for (i = 0; i < homeSkuArr.length; i++) {
			//document.getElementById(homeSkuArr[i]+'-cart').style.display = "none";
		}
			
	} else {
	
	
	//document.getElementById('expert_package-cart').style.display = 'none';

	elId = el+'-cart';

	/*
if (document.getElementById(elId).style.display == 'none') {
	
	var cartList = document.getElementById('ow_list');
		
	document.getElementById(elId).style.display = 'block';
	
	} else {
	
	document.getElementById(elId).style.display = 'none';
	
	}
*/
	
	}
	
}

function submitenter(e)
{
var keycode;
if (window.event) keycode = window.event.keyCode;
else if (e) keycode = e.which;
else return true;

if (keycode == 13)
   {
   document.getElementById('location_submit_button').click();
   return false;
   }
else
   return true;
}

</script>

<?php if (Mage::getSingleton('cms/page')->getIdentifier() != 'at-home-std-tests') { ?>
<link media="all" href="/skin/frontend/default/getstdtested/css/orderwidget.css" type="text/css" rel="stylesheet">
<?php } ?>

<div class="bg_white">
<form name="productWidget" method="post" action="/customroute/index/checkout">
	<?php if (Mage::getSingleton('cms/page')->getIdentifier() == 'at-home-std-tests') { ?>
		<div id="order_side_widget_home">
	<?php } else { ?>
		<div id="order_side_widget_lab">
	<?php } ?>
            <h3>Select your STD test(s)</h3>

			<?php if (Mage::getSingleton('cms/page')->getIdentifier() != 'at-home-std-tests') { ?>
            <div class="content">
            	<ul>
                    <li><input type="checkbox" value="79.0000" id="hiv-lab" onClick="updateWidgetTotal(this.id,11);" name="indiTest[hiv-lab]" /> <label for="hiv-lab">HIV Standard</label></li>
                	<li><input type="checkbox" value="149.0000" id="chlamydia-gonorrhea-lab" onClick="updateWidgetTotal(this.id,40);" name="indiTest[chlamydia-gonorrhea-lab]" /> <label for="chlamydia-gonorrhea-lab">Chlamydia &amp; Gonorrhea</label></li>
                    <li><input type="checkbox" value="149.0000" id="oral-genital-herpes-lab" onClick="updateWidgetTotal(this.id,42);" name="indiTest[oral-genital-herpes-lab]" /> <label for="oral-genital-herpes-lab">Oral &amp; Genital Herpes</label></li>
                    <li><input type="checkbox" value="89.0000" id="hepatitis-b-lab" onClick="updateWidgetTotal(this.id,7);" name="indiTest[hepatitis-b-lab]" /> <label for="hepatitis-b-lab">Hepatitis B</label></li>
                    <li><input type="checkbox" value="89.0000" id="hepatitis-c-lab" onClick="updateWidgetTotal(this.id,8);" name="indiTest[hepatitis-c-lab]" /> <label for="hepatitis-c-lab">Hepatitis C</label></li>
                    <li><input type="checkbox" value="89.0000" id="syphilis-lab" onClick="updateWidgetTotal(this.id,12);" name="indiTest[syphilis-lab]" /> <label for="syphilis-lab">Syphilis</label></li>
                    <li><input type="checkbox" value="179.0000" id="hiv-early-detection-lab" onClick="updateWidgetTotal(this.id,13);" name="indiTest[hiv-early-detection-lab]" /> <label for="hiv-early-detection-lab">HIV Early Detection *</label></li>
                </ul>
                <div class="clear">&nbsp;</div>
            </div> <!-- /.content -->
            
			<h4>Complete STD Tests Package</h4>
            <input id="expert_package_hidden" type="hidden" value="229.0000" name="pack_14">
            <div class="content">
            	<ul class="check">
                	<li>Chlamydia</li>
                    <li>Gonorrhea</li>
                    <li>HIV Standard</li>
                    <li>Syphilis</li>
                </ul>
                <ul class="check">
                	<li>Oral Herpes</li>
                    <li>Genital Herpes</li>
                    <li>Hepatitis B</li>
                    <li>Hepatitis C</li>
                </ul>
				<div class="cboth" style="padding: 10px 0 0 48px;">
					<input type="radio" id="expert_package" value="229.0000" onClick="updateWidgetTotal(this.id,14);" name="testPackage" />
					<label for="expert_package"><strong>ADD TO CART</strong></label>
				</div>
            </div> <!-- /.content -->
            
            <div class="total">
				<input type="submit" class="submit btn_orange_32_reflection" value="Checkout" />
            	<div class="total_content">Fastest Results!</div>
            </div>
            
			<?php } ?>
            
			<?php if (Mage::getSingleton('cms/page')->getIdentifier() == 'at-home-std-tests') { ?>
            <div class="content">
				<ul>
					<li>
						<input type="checkbox" value="105.0000" id="hiv-home" onClick="updateWidgetTotal(this.id,4);toggleCartElement(this.id);" name="homeTest[hiv-home]" />
						<label for="hiv-home">HIV Standard</label>
						<span class="order_side_widget_home_price">$105</span>
					</li>
					<li>
						<input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="165.0000" id="chlamydia-gonorrhea-home" onClick="updateWidgetTotal(this.id,44);toggleCartElement(this.id);" name="homeTest[chlamydia-gonorrhea-home]" />
						<label for="chlamydia-gonorrhea-home">Chlamydia &amp; Gonorrhea</label>
						<span class="order_side_widget_home_price">$165</span>
					</li>
					<li>
						<input <?php if (Mage::getSingleton('core/session')->getIsNnr()) { ?> disabled='disabled'<? } ?> type="checkbox" value="205.0000" id="trichomoniasis-home" onClick="updateWidgetTotal(this.id,3);toggleCartElement(this.id);" name="homeTest[trichomoniasis-home]" />
						<label for="trichomoniasis-home">Trichomoniasis</label>
						<span class="order_side_widget_home_price">$205</span>
					</li>
				</ul>
                <div class="clear">&nbsp;</div>
            </div> <!-- /.content -->
            
            <div class="total">
            	<input type="submit" class="submit btn_orange_32_reflection" value="Checkout" />
            	<div class="total_content">Free Priority Shipping!</div>
            </div>
			<?php } ?>
            
        </div>
        <input type="hidden" id="package" name="package" value="">
        </form>

		<?php if (Mage::getSingleton('cms/page')->getIdentifier() != 'at-home-std-tests') { ?>        
        <p class="cboth" style="padding: 35px 0 0 18px;"><small>
			* ABOUT HIV TESTING<br />
			The HIV early detection test is a DNA-based test that can detect the virus as early as two weeks after possible exposure. However, our physician's recommend pairing the early detection test with the HIV Standard test, which is considered the "gold standard" in HIV screening. However, it may take up to 12 weeks for the HIV Standard test to provide accurate results. Repeat HIV testing is recommended for sexually active adults with multiple partners or concern of exposure.
		</small></p>
		<?php } ?>        
        
        </div>