<div class="box box-4">

    <div class="col_3">
        <h3>Satisfied Patients</h3>
        <div class="quotation">
            <ul>
                <li>
                    <p>"I was treated very nicely, everything was very quick, I will recommend you to anyone who needs to be tested, your service was well worth the $90, for what I received. Thank you very much!"</p>
                    <span>- Richard Y, North Carolina</span>
                </li>
            </ul>

            <span class="nav">
                <a class="active" href=""></a>
                <a href=""></a>
                <a href=""></a>
            </span>
        </div>
    </div>

    <div class="col_3">
        <h3>Why Choose Us?</h3>
        <ul>
            <li>The most accurate tests on the market</li>
            <li>Fastest results in 3 to 5 days</li>
            <li>100% confidential – No affiliation with your medical or billing records</li>
            <li>Easy online scheduling &amp; private results portal</li>
            <li>Satisfaction guaranteed</li>
        </ul>
    </div>

    <div class="col_3 col_3_last">
        <h3>Sample Test Results</h3>
        <img src="/skin/frontend/default/getlabtested/images/sample_test.jpg" />
    </div>

</div>
