<div class="box_col b-8">
    <h2><span>Testing Centers</span><br />Near You</h2>
    <form id="zipcodeForm" name="zipcodeForm" class="fleft" method="post" action="/locate-testing-center">
        <input name="zip_code" type="zipcode" id="zipcode" value="Enter Zip Code" size="20" onfocus="this.value=''"/>
    </form>
    <a href="javascript:void(0);" class="b-find fleft" onclick="$('zipcodeForm').submit()">Find A Testing Center</a>
</div>

<div class="box_col b-3">
    <h2>Questions?<br /><span>Or To Order By Phone</span></h2>
    <span class="t1">CALL US AT</span><br />
    <span class="t2">(877) 317-3178</span>
    <p>M-F 7:00am - 6:30pm<br />Sat-Sun 9am-3pm CST</p>
</div>